### ISSUE TITLE
Finish step broken if nothing pushed to guest before

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#1011]
When there is no discover or prepare or execute step nothing does guest push. But finish wants to pull nonexistent directory then.

Simple `tmt run provision finish` fails in finish pull with 
```
stderr (4/4 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Warning: Permanently added '[127.0.0.1]:10052' (ED25519) to the list of known hosts.
rsync: [sender] link_stat "/var/tmp/tmt/run-082/plans/default" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1816) [Receiver=3.2.3]
rsync: [Receiver] write error: Broken pipe (32)
```

Note that this can be also hit by first calling provision and later calling finish e.g.
1. tmt run --id myrun  provision
2. <do something with the guest but don't use tmt 
3. tmt run --id myrun  finish (or tmt run --last finish)

There was no pull in finish before ec1d88b

**Comment by lukaszachy** [comment]
Hmm, we should rework push and workdir structure a bit.... Looks that pull/push is manipulating guests.yaml (and other tmt control files)

**Comment by psss** [comment]
> Hmm, we should rework push and workdir structure a bit....

Yes, you're right. I'm trying to partially address this in #1015 by pulling only selected directories. However, we need some more improvements in this area.
