### ISSUE TITLE
Please enhance the tmt by adding -oForwardX11=no to the ssh commands to avoid tmt hanging on hanging ssh connection

### ISSUE THREAD

**Issue by jirka-h** [psss/tmt#1023]
Hello,

I was testing the tmt to execute tests on the external system via ssh

```
tmt run -a -vvv -r plans --name /plans/stress-ng_perf provision --how connect --guest HOST
```

The provisioning step never ended [1] and the job got stuck. 

Adrian has helped me to find the root cause. This command 
```
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@HOST cat /etc/os-release
```

never ended. It was because I had X11 forwarding enabled in my `.ssh/config`

```
ForwardX11 yes
```

You can reproduce it like this:
```
ssh -X HOST cat /etc/os-release
```
In my case, HOST was running `RHEL-8.5.0` and I have Fedora 34 on my laptop. (ssh client and server versions are important). 

**Could you please enhance the tmt by adding  `-oForwardX11=no` to the ssh commands to avoid this?**

This commands works as expected and does not hang:
```
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oForwardX11=no root@HOST cat /etc/os-release
```

Here is some more context:
[stackoverflow.com](https://stackoverflow.com/questions/13634697/openssh-client-hangs-on-logout-when-forwarding-x-connections
)
[snailbook.com](http://www.snailbook.com/faq/background-jobs.auto.html
)

Thanks a lot!
Jirka

[1] tmt hangs in the provision phase:
```
    provision
       how: connect
       order: 50
       guest: HOST
       user: root
       key: not provided
```

**Comment by psss** [comment]
Thanks for reporting this. Using `-oForwardX11=no` seems like a reasonable default to me. Going to create the pull request right away.

**Comment by jirka-h** [comment]
Thanks for a quick resolution!
