### ISSUE TITLE
tmt run --id `--all` vs `-all` -> --all respects --id but -all doesn't  

### ISSUE THREAD

**Issue by sbertramrh** [psss/tmt#1035]
provisioning with 1minutetip does not increment the run id, like other methods. Trying to force it using --id, the tmt switch, is ignored.

**Comment by lukaszachy** [comment]
Hm, can't reproduce with tmt-1.10.0
`tmt run finish provision -h minute` created /var/tmp/tmt/run-135 (last run was run-134)
`tmt run --id run-140 finish provision -h minute` created /var/tmp/tmt/run-140

**Comment by sbertramrh** [comment]
Thanks @lukaszachy I didn't think to check my version before. i am on
[sbertram@sbertram wrapper]$ tmt --version
tmt version: 1.9.0 (599b9a1)

upgraded:
[sbertram@sbertram wrapper]$ tmt --version
tmt version: 1.10.0 (15f910b)

Already had a run-001 from a previous test and it still tries to use the old  run, not incrementing.

```
tmt run -all provision --how minute --image=1MT-RHEL-9.0.0-20220117.0 --flavor=ci.memory.medium
/var/tmp/tmt/run-001

/plans/default
    discover
        status: done
        summary: 1 test selected
    provision
        status: done
        summary: 1 guest provisioned
    prepare
        status: done
        summary: 0 preparations applied
    execute
        status: done
        summary: 1 test executed
    report
        how: display
        summary: 1 error
    finish
        status: done
        summary: 0 tasks completed

total: 1 error
```

And when passing id I still see the same behavior. Could this be because I am on rhel8.5 csb?
```
[sbertram@sbertram wrapper]$ tmt run --id minute-001 -all provision --how minute --image=1MT-RHEL-9.0.0-20220117.0 --flavor=ci.memory.medium
/var/tmp/tmt/run-001

/plans/default
    discover
        status: done
        summary: 1 test selected
    provision
        status: done
        summary: 1 guest provisioned
    prepare
        status: done
        summary: 0 preparations applied
    execute
        status: done
        summary: 1 test executed
    report
        how: display
        summary: 1 error
    finish
        status: done
        summary: 0 tasks completed

total: 1 error
```

When i then removed --all it worked but only did the provision step, which i guess is expected. i then ran it with --all again and it was able to complete the test. But it seems --all is what is causing the issue with --id.
```
[sbertram@sbertram wrapper]$ tmt run --id minute-002  provision --how minute --image=1MT-RHEL-9.0.0-20220117.0 --flavor=ci.memory.medium
/var/tmp/tmt/minute-002

/plans/default
    provision
        how: minute
        image: 1MT-RHEL-9.0.0-20220117.0
        flavor: ci.memory.medium
        auto-select-network: False
        skip-prereserve: False
        distro: Red Hat Enterprise Linux 9.0 Beta (Plow)
        summary: 1 guest provisioned
[sbertram@sbertram wrapper]$ tmt run --id minute-002  -all provision --how minute --image=1MT-RHEL-9.0.0-20220117.0 --flavor=ci.memory.medium
/var/tmp/tmt/minute-002

/plans/default
    discover
        how: fmf
        directory: /home/sbertram/gitstuff/kernel
        path: selftests/wrapper
        summary: 1 test selected
    provision
        status: done
        summary: 1 guest provisioned
    prepare
        how: install
        summary: Install required packages
        name: requires
        package: beakerlib
        how: install
        summary: Install recommended packages
        name: recommends
        package: wget, ethtool, python3 and 17 more
        summary: 2 preparations applied
    execute
        how: tmt
        progress: / [1/1]
```

**Comment by lukaszachy** [comment]
OK, finally reproduced (but it is not related to the minute plugin).
Steps: `tmt init -t full` and `tmt run --id ZZZ -all` -> runs in last run id directory. However `tmt run --id ZZZ --all` -> runs in ZZZ run directory.
The difference is in `-all` vs `--all`.

**Comment by lukaszachy** [comment]
I am assuming click parses `-all` as `-a -l`.

**Comment by sbertramrh** [comment]
heh a typo on my part. thanks. so in a perfect world it would have said unknown option -all but instead it possibly interpreted it as you said, -a -l.

**Comment by lukaszachy** [comment]
And it looks to be an expected feature - https://github.com/pallets/click/issues/955 when `-all` translates to `-a -l -l` and is accepted.
