### ISSUE TITLE
Hard to enable virtual provision under Fedora 30

### ISSUE THREAD

**Issue by psss** [psss/tmt#105]
Currently it's not easy to make virtual provision working under Fedora 30. The `rsync-back` plugin fails with the [known error](https://tmt.readthedocs.io/en/latest/questions.html), uninstalling `rubygem-fog-core` results in uninstalling vagrant. Then install `vagrant` again and try `vagrant plugin install vagrant-libvirt` which fails as well:

    $ vagrant plugin install vagrant-libvirt
    Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
    Fetching formatador-0.2.5.gem
    Fetching excon-0.72.0.gem
    Fetching builder-3.2.4.gem
    Fetching fog-core-1.43.0.gem
    Fetching mini_portile2-2.4.0.gem
    Fetching nokogiri-1.10.7.gem
    Building native extensions. This could take a while...
    Fetching multi_json-1.14.1.gem
    Fetching fog-json-1.2.0.gem
    Fetching fog-xml-0.1.3.gem
    Fetching ruby-libvirt-0.7.1.gem
    Building native extensions. This could take a while...
    Vagrant failed to properly resolve required dependencies. These
    errors can commonly be caused by misconfigured plugin installations
    or transient network issues. The reported error is:

    ERROR: Failed to build gem native extension.

        current directory: /home/user/.vagrant.d/gems/2.6.5/gems/ruby-libvirt-0.7.1/ext/libvirt
    /usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20200210-14111-10qat5h.rb extconf.rb
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
            --with-opt-dir
            --without-opt-dir
            --with-opt-include
            --without-opt-include=${opt-dir}/include
            --with-opt-lib
            --without-opt-lib=${opt-dir}/lib64
            --with-make-prog
            --without-make-prog
            --srcdir=.
            --curdir
            --ruby=/usr/bin/$(RUBY_BASE_NAME)
            --with-libvirt-include
            --without-libvirt-include
            --with-libvirt-lib
            --without-libvirt-lib
            --with-libvirt-config
            --without-libvirt-config
            --with-pkg-config
            --without-pkg-config
    extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

    To see why this extension failed to compile, please check the mkmf.log which can be found here:

    /home/user/.vagrant.d/gems/2.6.5/extensions/x86_64-linux/2.6.0/ruby-libvirt-0.7.1/mkmf.log

    extconf failed, exit code 1

    Gem files will remain installed in /home/user/.vagrant.d/gems/2.6.5/gems/ruby-libvirt-0.7.1 for inspection.
    Results logged to /home/user/.vagrant.d/gems/2.6.5/extensions/x86_64-linux/2.6.0/ruby-libvirt-0.7.1/gem_make.out

Seems `libvirt-devel` is another un-documented dependecy. We should make this much, much easier. @pvalena, what would you recommend? Would installing from copr help here?

**Comment by pvalena** [comment]
Wow, I didn't even know you're having this issue. Anyway, If one does suggest a fix / or implement it in some `tmt/{scripts,helpers,idk}`, would it suffice?

In a few ~days?~ I'll have the plugin packaged (which will solve all our problems[tm]) in my COPR, se we could use it as the official solution?

In general what you're encountering is the lack of `ruby-devel`, `gcc`, (other devel tools), `redhat-rpm-config`. But users shouldn't see this. When I get through the packaging process I'll try to add the plugin for all Fedoras, so our 'installation' would just work(tm).

See our [Ferdora developer guide](https://developer.fedoraproject.org/tech/languages/ruby/gems-installation.html) for more about `gems` (yes, plugins are just `gems`).

**Comment by pvalena** [comment]
>  If one does suggest a fix

I meant myself of course.

**Comment by pvalena** [comment]
I've also written my recommended _temp-fix_ [here](https://github.com/psss/tmt/pull/31#issuecomment-550067874).

**Comment by psss** [comment]
> Wow, I didn't even know you're having this issue. Anyway, If one does suggest a fix / or implement it in some `tmt/{scripts,helpers,idk}`, would it suffice?

I think, for now, documenting this well should be sufficient.

> In a few _days(?)_ I'll have the plugin packaged (which will solve all our problems[tm]) in my COPR, se we could use it as the official solution?

That would be definitely better! Ideally we should have everything directly in Fedora repos to make the user experience as smooth as possible.

> In general what you're encountering is the lack of `ruby-devel`, `gcc`, (other devel tools), [redhat-rpm-config](https://src.fedoraproject.org/rpms/redhat-rpm-config) . But users shouldn't see this. When I get through the packaging process I'll try to add the plugin for all Fedoras, so our 'installation' would just work(tm).

Thanks, having the plugin directly in Fedora would be the best solution, I guess.

**Comment by psss** [comment]
Hm, tried to install dependencies and development packages but still unsuccessful:

    podman run -it --rm fedora:30
    dnf install -y vagrant --setopt=install_weak_deps=False
    dnf group install -y 'C Development Tools and Libraries'
    dnf install -y redhat-rpm-config
    dnf install -y ruby-devel rubygem-{formatador,excon,builder,ruby-libvirt}

@pvalena, any further packages needed to install a plugin?

**Comment by pvalena** [comment]
rubygem-nokogiri was missing: https://gist.github.com/pvalena/9fd8cf6a613a026001b365c1122ac23d

**Comment by pvalena** [comment]
@psss but we don't need to build any binary extensions! So simplified (better) version is:

https://gist.github.com/pvalena/e74b7d7d80e42cb4929dbe8f3f078603

IOW: 
```console
$ dnf install -y --setopt=install_weak_deps=False \
  vagrant rubygem-{formatador,excon,builder,ruby-libvirt,nokogiri,multi_json}
```

**Comment by pvalena** [comment]
And all of that is needed just until Vagrant-libvirt releases new version.

**Comment by psss** [comment]
Thanks for investigating this. So for now let's fix this by docs update. Better fix is on the way.
