### ISSUE TITLE
Unable to `provision --how virtual` under `centos-stream-9`

### ISSUE THREAD

**Issue by psss** [psss/tmt#1096]
When running a minimal template on a `centos-stream-9` box I get the following error:

    libguestfs: error: could not get libvirt domain capabilities: internal error:
    missing 'nvram-template' in '/usr/share/qemu/firmware/50-edk2-ovmf-amdsev.json' [code=1 int1=-1]

@frantisekz any idea what might be wrong there?

**Comment by frantisekz** [comment]
This will probably be the cause: https://bugzilla.redhat.com/show_bug.cgi?id=2057769

**Comment by frantisekz** [comment]
> This will probably be the cause: https://bugzilla.redhat.com/show_bug.cgi?id=2057769

The mentioned issue seems to be fixed, do you have some free cycles to take a look @psss , or shall I give it a try?
