### ISSUE TITLE
Multiple tierX tags when converting tests

### ISSUE THREAD

**Issue by hegerj** [psss/tmt#116]
According to specification [1] `tier` attribute is a string with a single value. This should be exported as a tag to nitrate (i.e.: `tier: 1` should become `Tier1` tag in nitrate test case tags) [2]. 
Therefore it implies that the other direction (converting tests from nitrate) should create `tier: X` attribute in fmf file.
The issue is that nitrate test case can have multiple `TierX` tags (common scenario) - how should this scenario be mapped into `tier` attribute? 

[1] https://tmt.readthedocs.io/en/latest/spec/tests.html#tier
[2] https://tmt.readthedocs.io/en/latest/stories/cli.html#convert

**Comment by psklenar** [comment]
It could happen that test case has more tier tags, by accident.
There are many variant what to do, what about:

convert could work to chose ONE tier tag with 'higher priority' + write WARNING

**Comment by hegerj** [comment]
just for clarity, 'higher priority' means smaller interer, i.e.: Tier1 has higher priority than Tier2
