### ISSUE TITLE
tmt tests export --nitrate: Allow case creation

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#117]
When I am writing new test, I want to be able specify everything using tmt/fmf and let tmt create the test case on nitrate server.

Otherwise for new test I  would need to manually (or by other tool) create some test case, and either manually create the tcms attribute in fmf file, or let the tmt tests convert import it.

**Comment by lukaszachy** [comment]
@psss What are you thoughts about this? Might be handy for adoption.

**Comment by psss** [comment]
Agreed, this might be handy during the transition period when we still need nitrate test cases. The `tmt test export` seems the best place. It could be something like this:

    tmt test export --format nitrate --create

**Comment by hegerj** [comment]
@psss How can I determine which file defines test case (in order to write to it newly created extra-nitrate id).

**Comment by psss** [comment]
Each fmf node object keeps the list of files from which metadata has been constructed in `sources`. If I remember correctly, the order should follow the inherit steps so the last item from the list should be your friend :)

**Comment by psss** [comment]
Implemented by #185.
