### ISSUE TITLE
Shall tmt test import use extra prefix for tcms and task as well?

### ISSUE THREAD

**Issue by psss** [psss/tmt#120]
Currently `pepa` and `hardware` are imported with the `extra` prefix. Keys `tcms` and `task` are also not included in the L1 metadata specification. Should we use prefix for them as well? @thrix, @lukaszachy, @hegerj, what do you think?

**Comment by hegerj** [comment]
Either add them to the specification or give them prefix, current state is inconsistent.
Because it seems that nitrate isn't going to be part of testing infrastructure in the future it makes more sense to me to add the prefix rather than adding it to specification

**Comment by psss** [comment]
Agreed. Makes better sense to me. Going to add the prefix.
