### ISSUE TITLE
Use testinfo.desc when importing beakerlib tests

### ISSUE THREAD

**Issue by hegerj** [psss/tmt#131]
Instead of reading Makefile directly we could use testinfo.desc file.
It would require extra system call when converting which might take more time, however it would solve issue with Makefiles that use variables to create variables we read.

@lukaszachy  you mentioned reading testinfo.desc makes more sense to you, do you have another use case than the one I mentioned?

**Comment by psss** [comment]
Not sure about his. It would probably bring an additional dependency as Makefiles quite often contain:

    include /usr/share/rhts/lib/rhts-make.include

So `rhts-test-env` which is not in Fedora would need to be installed on the box to make this working.

**Comment by lukaszachy** [comment]
In the past I've run into examples where people were very good users of Make and modified the 'testinfo.desc' to suite their needs -> a lot of variable expansions. 
Keep in mind that only the content of produced testinfo.desc it the authority source for Beaker (make bkradd) and provides initial values for TCMS as well.

**Comment by hegerj** [comment]
There is no additional dependency needed (apart from make). If we made 
`include /usr/share/rhts/lib/rhts-make.include`
optional or didn't include at all only thing we need to declare is variable
`METADATA=testinfo.desc`
and it should work.
And it could be done 'on-the-fly' with no changes to Makefile needed from test maintainers.

**Comment by psss** [comment]
So you mean to adjust the `Makefile` (or better its copy) by removing the include, defining the `METADATA` variable and removing `rhts-lint` so that you can actually do `make testinfo.desc`?

**Comment by hegerj** [comment]
Exactly, reading Makefile as a string, doing necessary changes and then feeding it to 
`make testinfo.desc -f -`
should work (@lukaszachy thought of it and tested it).

**Comment by psss** [comment]
I see. That makes sense to me. In this way we should be able to handle more special / custom user setups in the `Makefile`. Plus one for this implementation.

**Comment by psss** [comment]
Support for `testinfo.desc` parsing merged in 3dff02a.
