### ISSUE TITLE
Support different options for individual plugins

### ISSUE THREAD

**Issue by psss** [psss/tmt#135]
We need to find the best way how to support different set of options for different step implementations. We could somehow hack option preparation before `click` takes care of processing options:

```python
import click
import sys

@click.group()
def main():
    pass

@main.command()
@click.option('-h', '--how', help='Prepare method.')
def prepare(how, **kwargs):
    print(f'playbook: {kwargs.get("playbook")}')
    print(f'script: {kwargs.get("script")}')

if __name__ == '__main__':
    arguments = ' '.join(sys.argv)
    print(arguments)
    if 'prepare --how ansible' in arguments:
        prepare = click.option('-p', '--playbook', help='Playbook.')(prepare)
    if 'prepare --how shell' in arguments:
        prepare = click.option('-s', '--script', help='Shell script.')(prepare)
    main()
```

Except for the hack (and the need to adjust somehow unit tests to work with this) something like that seems doable. Another option could be to provide separate subcommand for each implementation:

    discover-fmf
    discover-shell
    provision-local
    provision-virtual
    provision-container
    provision-container
    ...

This would, however, result in many subcommands in the usage message and also on the command line you would always have to provide the full subcommand name:

    tmt run prepare-ansible --playbook book.yaml

And for selecting individual steps you would probably have to use the full name as well:

    tmt run discover-fmf

I don't like this much. Any other ideas how to solve this? Any expert on `click` who could help with implementing this purely in it?

**Comment by psss** [comment]
@thrix, @pvalena, @lukaszachy, @hegerj, please share your thoughts.

**Comment by pvalena** [comment]
I have already some of "workings" we might use exactly for this, in a form of a validator:

https://github.com/psss/tmt/blob/master/tmt/steps/prepare/__init__.py#L19

https://github.com/psss/tmt/blob/master/tmt/steps/prepare/__init__.py#L43

Which is IMO exactly what we need in this case.

**Comment by thrix** [comment]
@psss I will try to take a look, but I am also not a click expert :(

**Comment by thrix** [comment]
@psss I would go first maybe with hack and maybe we can find a better solution later? it would be awesome if all plugins could maybe provide these options by themselves in a special function instead of having this code somwhere near main?

**Comment by psss** [comment]
Yes, definitely agreed. The plugin-specific option handling will be part of the plugin itself.

**Comment by pvalena** [comment]
@psss If i'm not mistaken, this solves only the UI part (mostly). Have you considered pairing it with the validator (globally) that I've written? That could fit very nicely IMO...
