### ISSUE TITLE
Documentation incorrect on "enabled:" attribute

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#141]
I noticed the documentation https://tmt.readthedocs.io/en/latest/spec/tests.html says the enabled attribute can be either "yes" or "no" but tmt test convert actually creates "enabled: true" and the console output says "enabled: True" with a capital "T" 
It should probably all be the same to avoid confusion.

**Comment by hegerj** [comment]
actually yaml accepts bool values `yes`, `true`, `on`, `y` as `True` and `no`, `false`, `off`, `n` as `False` (with various upper case variations)
It's confusing but it is according to specification: https://yaml.org/type/bool.html

**Comment by psss** [comment]
So the canonical `yaml` version for `True` seems to be `y` which I don't like to have as an example. The `yes` seems to be the closest choice then. Or anyone has a better idea?
