### ISSUE TITLE
Tmt test convert breaks if test is disabled in TCMS

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#142]
When converting a test which has Status: DISABLED set in TCMS the resulting main.fmf file is missing most of the information from TCMS:
contact
enabled attribute
relevancy
tags
task
tcms
I think this is incorrect, the correct behaviour probably should be just setting the enabled: false in main.fmf and still including all the other information.
Setting status to NEED_UPDATE and PROPOSED has the same odd effect as DISABLED.

**Comment by hegerj** [comment]
I think we decided against importing cases that are not `CONFIRMED` to avoid adding too many irrelevant/old cases to new metadata system (when one test has many cloned cases in nitrate, when some of them are for test scenarios that are not supported anymore for example)
Are you talking about situation when test has only one case in nitrate and it not set to `CONFIRMED`?

**Comment by psss** [comment]
This looks like a bug. Looking at the [implementation](https://github.com/psss/tmt/blob/master/tmt/convert.py#L185) it should work as you suggested.

**Comment by psss** [comment]
But during [search](https://github.com/psss/tmt/blob/master/tmt/convert.py#L147) disabled test cases are filtered out. I think we could add an option to choose which tests should be considered. For example:

    tmt test import --enabled
    tmt test import --disabled

By default all tests would be imported. What do you think?

**Comment by Athwale** [comment]
hegerj: Yes I encountered the problem while converting a test which has only one case in TCMS.
Tests in TCMS can be set to these states when for example the test has to be fixed, but it can not be done right now.

**Comment by lukaszachy** [comment]
Personally I am against importing non-confirmed cases  by default. Either are broken, or were created by accident (and setting to disabled and unlink from plan was easiest way to "delete" them).

Option to allow import also non-confirmed might be useful though. But it should allow specify status.
CONFIRMED == enabled, DISABLED == disabled but what about PROPOSED and NEED_UPDATE? They are something between.

**Comment by hegerj** [comment]
How about we would, by default, import all cases besides `DISABLED`, and set `enabled: false` for `NEED_UPDATE` and `PROPOSED`?
--disabled would also import `DISABLED` cases with `enabled: false`

**Comment by Athwale** [comment]
I like this last suggestion from hegerj.

**Comment by psss** [comment]
Agreed. That looks like the best solution.
