### ISSUE TITLE
Exporting nitrate test might cause inconsistency

### ISSUE THREAD

**Issue by hegerj** [psss/tmt#147]
Because fmf has fewer test states than nitrate (True/False - confirmed/disabled/proposed/need update) it might happen that importing - exporting will cause inconsistency due to new rules regarding to import (#142). I am not fan of this I am afraid there is no way around.

The question then is to which nitrate state should be cases with `enabled: False` imported?
Personally I think `PROPOSED` is best but I am not sure, what is your opinion @psss  @Athwale?

**Comment by hegerj** [comment]
It would be nice to resolve this issue before #118 is merged.

**Comment by psss** [comment]
I'd say if the current nitrate status is not `confirmed` and test is not `enabled` I would not touch nitrate status but keep it as it is. If nitrate status is `confirmed` I would change it probably to `disabled`. Why would be `proposed` better?

**Comment by hegerj** [comment]
I didn't consider checking the current nitrate status.
The way you proposed seems to be the best to me.

**Comment by hegerj** [comment]
Fixed in #118 by b919cfb

**Comment by psss** [comment]
Resolved about a month ago.
