### ISSUE TITLE
testcloud provisioner should have a default image

### ISSUE THREAD

**Issue by t184256** [psss/tmt#154]
testcloud provisioner should have a default image. If you decide against having one, the example in `docs/examples.rst` should be modified.

**Comment by psss** [comment]
Agreed to always have a default image. That would be nice/handy for `podman` as well. @thrix, what do you say?

**Comment by thrix** [comment]
Yes, I guess by default it will map to what --image fedora does ....

**Comment by psss** [comment]
Fixed in 10a0c9e.
