### ISSUE TITLE
Unable to run tests using testcloud on RHEL8

### ISSUE THREAD

**Issue by psss** [psss/tmt#167]
I've installed `tmt` on a fresh RHEL8 box:

    dnf copr enable -y psss/tmt
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    dnf install -y tmt-testcloud testcloud
    systemctl start libvirtd

And tried to run the base template:

    mkdir /tmp/base
    cd /tmp/base
    tmt init -t base
    tmt run -ad provision -h virtual.testcloud -i fedora

Which failed with the following traceback:

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/tmt/base.py", line 341, in go
        step.go()
      File "/usr/lib/python3.6/site-packages/tmt/steps/provision/__init__.py", line 59, in go
        guest.go()
      File "/usr/lib/python3.6/site-packages/tmt/steps/provision/testcloud.py", line 268, in go
        self.instance.spawn_vm()
      File "/usr/lib/python3.6/site-packages/testcloud/instance.py", line 392, in spawn_vm
        conn.defineXML(domain_xml)
      File "/usr/lib64/python3.6/site-packages/libvirt.py", line 3743, in defineXML
        if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
    libvirt.libvirtError: Cannot check QEMU binary /usr/bin/qemu-kvm: No such file or directory

And finally nothing provides qemu-kvm:

    # dnf install /usr/bin/qemu-kvm
    No match for argument: /usr/bin/qemu-kvm
    Error: Unable to find a match: /usr/bin/qemu-kvm

What do we do now? :-)

**Comment by pvalena** [comment]
It works fine with vagrant-libvirt, right?

**Comment by psss** [comment]
Unfortunately not:

    Run command 'vagrant plugin install vagrant-libvirt'.
    out: Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
    err: Vagrant failed to properly resolve required dependencies. These
    err: errors can commonly be caused by misconfigured plugin installations
    err: or transient network issues. The reported error is:
    err: Unresolved dependency found during sorting - unf (>= 0) (requested by domain_name-0.5.20190701)

Uninstalling `vagrant-libvirt rubygem-fog-core` did not help (were not installed).

**Comment by pvalena** [comment]
Well, as I've sent you previously. You have to install all necessary plugins from my COPR, in case of RHEL8: `dnf install vagrant-libvirt vagrant-rync-back vagrant-managed-servers`

**Comment by psss** [comment]
This has been fixed by cf68d802013525a43d8d8d7e896d840500ea15dd.
