### ISSUE TITLE
enabled: true/false attribute does not work

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#170]
Setting the enabled: true/false attribute in main.fmf has no effect on tests being selected. 
tmt-0.11-1.fc31.noarch

enabled: true
--------------------
tmt run discover
/var/tmp/tmt/run-040

/ci/test
    discover
        how: fmf
        name: tier1
        repository: git://pkgs.devel.redhat.com/tests/lftp
        filter: tier: 1
        tests: 4 tests selected

enabled: false
--------------------
tmt run discover
/var/tmp/tmt/run-041

/ci/test
    discover
        how: fmf
        name: tier1
        repository: git://pkgs.devel.redhat.com/tests/lftp
        filter: tier: 1
        tests: 4 tests selected

**Comment by psss** [comment]
Thanks for reminding this. Should be now fixed in master.
