### ISSUE TITLE
Provide easy and robust way to run guest setup commands

### ISSUE THREAD

**Issue by martinpitt** [psss/tmt#1732]
In the testing farm, we [struggle a lot](https://gitlab.com/testing-farm/gluetool-modules/-/issues/12) with calling tmt to run a test with injecting additional guest setup commands (install COPR repositories and packages, install a koji build, etc.). The currently generated `tmt-reproducer.sh` files hook into the `prepare` step:

    prepare --how shell --script '...'

but that overwrites a plan's own `prepare:` step, and thus we need to drop that. In [the issue above](https://gitlab.com/testing-farm/gluetool-modules/-/issues/12) I was experimenting with various alternatives, like running `prepare` twice (doesn't work, and `--force` is broken).

It seems the only robust way to do that is to call tmt *three* times:
```sh
tmt run --until provision provision --how virtual --image Fedora-37 plan --name '^/plans/name$'
tmt run --last login < guest-setup.sh
tmt run --last --since prepare
```

But this is a bit ugly -- it's easy to get wrong with repeated execution or with copy&paste.

I also found that to work:
```sh
cat guest-setup.sh | tmt run --until report provision --how virtual --image Fedora-37 login --step provision plan --name '^/plans/name$'
```
that's simpler, but brittle:  It assumes that no other step except login reads from stdin.

I also tried this:
```sh
cat guest-setup.sh | tmt run --until report provision --how virtual --image Fedora-37 login --step --command 'curl https://piware.de/tmp/guest-setup.txt | bash -ex' provision plan --name '^/plans/all/second$'
```

but that fails:
```


Usage: tmt run [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
Try 'tmt run --help' for help.

Error: No such command 'curl https://piware.de/tmp/guest-setup.txt | bash -ex'.
```
and we also don't want to do that anyway, as it's not a given that `curl` exists in the testbed.

So, what I am asking for is a documented, tested, and recommended way to run additional guest setup (after provision, before prepare) in the testbed that *does not* collide with the plan. Something like this would be nice:

```sh
tmt run --until report provision --how virtual --image Fedora-37 login --step --script guest-setup.sh provision plan --name '^/plans/name$'
```
which would read `guest-setup.sh` and feed it into the shell. Or something equivalent, I'm not that fussed about the syntax.

Thanks for considering!

**Comment by martinpitt** [comment]
I'm now using the hackish 3-part command in https://gitlab.com/testing-farm/gluetool-modules/-/merge_requests/366 . Some hint/feedback about this would be much appreciated!

**Comment by thrix** [comment]
@martinpitt thanks for the report, it seems like if `tmt` modify / add (instead of overwriting) steps into prepare, that would also solve the problem right?

And actually we want to do it anyway.

**Comment by thrix** [comment]
Yep, this responsibility will move over to `tmt`, there is no question on that. And it will need to happen soon enough, as it will be required for us to enable multi-host testing.

**Comment by psss** [comment]
Decision from the hacking session: Document what's possible and do the proper reproducer implementation using support for inserting prepare step on the command line #68.

**Comment by martinpitt** [comment]
@psss That seems fine to me, thanks!

**Comment by thrix** [comment]
Documented here: https://github.com/teemtee/tmt/pull/1969

**Comment by thrix** [comment]
So, we document the current way @martinpitt has discovered, at least for the start.

Once we can inject/add/append prepare steps (not overwrite the whole steps) this might not be needed, we will see.

That will happen anyway (we need it for other use cases), so we do not need to keep this issue open.
