### ISSUE TITLE
Document clearly the usage L1/L2 metadata for people not knowing BaseOS QE tests

### ISSUE THREAD

**Issue by thrix** [psss/tmt#180]
After speaking with @stefwalter, we should try to make the onboarding to FMF easier for people who do not know the concept of L1/L2 metadata. Seems it is just too much information for them to understand. Moreover people wanting to add a simple tests can just write it in L2 metadata and they do not need to understand why there is L1 metadata, and what is the really the use case.

I am opening this issue, so we can try to find a way how to make the documentation more easy for these cases.

**Comment by psss** [comment]
Which documentation should be improved? The [testing farm docs](https://packit.dev/testing-farm/#smoke-test) already cover the simple smoke test scenario right at the start. The same applies to the internal Quick Start Guide. I don't see much L1/L2 terminology there. Both basically say:

Create template:

    tmt init --template mini

Adjust the script as desired:

    summary:
        Basic smoke test
    execute:
        script: tmt --help

Commit and you're done. How can we simplify more?

**Comment by psss** [comment]
I believe this has been covered by #877. The [second chapter](https://tmt.readthedocs.io/en/latest/guide.html#under-the-hood) of the guide now clearly describes what are plans (L2) and tests (L1).
