### ISSUE TITLE
More verbose/debug prepare:ansible

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#191]
I wanted to make sure what has happened in ansible playbook -> I need it to run in verbose mode.
Even with `tmt run -d` there is no appropriate output.

Please add a way to configure verbosity of ansible prepare from commandline.

**Comment by psss** [comment]
I think it would make sense to support `-dd`, `-ddd` or something like that in general. Using `self.opt('debug')` one could check exact debug level and adjust behaviour based on that.

**Comment by psss** [comment]
Should be fixed by #210.
