### ISSUE TITLE
ERROR  Unable to find tree root

### ISSUE THREAD

**Issue by hroncok** [psss/tmt#2]
```
[python-virtualenv (py34-patch %)]$ git remote -v
churchyard	ssh://pkgs.fedoraproject.org/forks/churchyard/rpms/python-virtualenv.git (fetch)
churchyard	ssh://pkgs.fedoraproject.org/forks/churchyard/rpms/python-virtualenv.git (push)
origin	ssh://churchyard@pkgs.fedoraproject.org/rpms/python-virtualenv (fetch)
origin	ssh://churchyard@pkgs.fedoraproject.org/rpms/python-virtualenv (push)
[python-virtualenv (py34-patch %)]$ git branch 
  16.6.1
  master
  nopy2
* py34-patch
  test38
  you_shall_not_pass
[python-virtualenv (py34-patch %)]$ tmt discover
 ERROR  Unable to find tree root for '/home/churchyard/rpmbuild/fedora-scm/python-virtualenv'.
```

**Comment by psss** [comment]
This means no config was found. Just enter one of the directories with examples for quick experimenting. The message should say more clearly that no metadata have been found.

**Comment by hroncok** [comment]
Oh. this is maybe a mismatch of expectations and reality then. i came to test this tool on my package with CI.

**Comment by psss** [comment]
I see. This is for now just a very early prototype, basically an outline. To start somewhere and give idea of how the command line interface could/would look like. Feel free to comment drafted options/subcommands if something like that would work for you. Also, so far we haven't planned support for the Standard Test Interface. We can consider later to provide some kind of backward-compatibility support as well.

**Comment by hroncok** [comment]
Can I use the test metadata specification (L1 and L2) to define my Fedora CI tests today?

**Comment by psss** [comment]
Not yet, but we're getting close. At Flock we've [presented](https://flock2019.sched.com/event/SIGO/concise-extensible-and-human-friendly-configuration-for-testing-and-gating) a simple prototype for github pull requests with packit integration. Fedora CI and RHEL CI are our next steps where we want to enable this. This library/tool will be part of that.
