### ISSUE TITLE
Allow to report results in xunit format

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#203]
A lot of ci/cd systems has integration with xunit and makes the life easier, e.g. [gitlab](https://docs.gitlab.com/ee/ci/junit_test_reports.html) can highlight new failures.

Please make option to store results in xunit format (similar to `pytest --junitxml=report.xml`)

Open question is mapping to testsuite and test case (for beakerlib with phases). 
Could this be additional option?

**Comment by psss** [comment]
Makes definitely sense. Should be one of the `report` plugins. The config could look like this:

    report:
        how: xunit
        file: <path-to-the-file>

Regarding beakerlib phases, what about using what's currently sent on message bus and displayed in the dashboard?

**Comment by lukaszachy** [comment]
> Regarding beakerlib phases, what about using what's currently sent on message bus and displayed in the dashboard?

As a default OK. But I think 'phase' is used only in our tooling.

My use case - Wrapper around upstream test suite written in beakerlib. Phases: setup, cleanup and each upstream test has its own test phase (e.g. in python: each test_*py has its phase called test_*py). So by using e..g reportportal  I can track each test_*  separately (and have history ;)

Or say our bkr workflow - one huge runtest.sh (and as it needs same setup I don't think is is wrong to have it in one long bash script) - I'd prefer for gitlab to parse xunit and highlight which one exactly failed. And for that reason it needs to be part of common xunit definition.

For above it seems that tmt.run is xunit.testsuites, each tmt.test is xunit.testsuite and each phase is xunit.testcase

**Comment by psss** [comment]
Hmmm, this is a bunch of very good points. Having the ability to somehow specify test granularity so that it makes the most sense for tracking the history would be a nice feature. We can start with some reasonable defaults for individual use cases (such as pytest suites or beakerlib phases) and in the future possibly also provide user with a way how to configure the granularity level per plan.

**Comment by lukaszachy** [comment]
Related question:
What should be done if script can already produce xunit? (e.g. `shell --script pytest --junit=FILE`)? 
Is there a way how to pull that file? 
Should it be brand new report plugin?
