### ISSUE TITLE
In prepare: Trying to enable: Prepare is confusing at best

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#214]
My plan contains `prepare: how: ansible` and `tmt run` prints
```
prepare
        Trying to enable: Prepare
        Trying to enable: Prepare
```

Could it be changed into more informative text? I believe one is 'require & beakerlib' installation, the other is my own prepare (ansible). If that is true then I would expect text as
```
prepare
   Trying to enable: Installing steps requires
   Trying to enable: Ansible with playbook XXXXX
```

**Comment by psss** [comment]
I'll take care of this as part of the `prepare` step conversion into a dynamic plugin.

**Comment by psss** [comment]
Here's an example output for the `/plans/helps` plan setup:

    prepare
        how: shell
        script: sudo dnf install -y 'dnf-command(copr)'
        script: sudo dnf copr enable -y psss/tmt
        script: sudo dnf install -y tmt
        summary: 1 preparation applied

Now with debug level one:

    prepare
        workdir: /var/tmp/tmt/run-447/plans/helps/prepare
        how: shell
        script: sudo dnf install -y 'dnf-command(copr)'
            Execute command 'sudo dnf install -y 'dnf-command(copr)'' on guest '10.0.138.247'.
        script: sudo dnf copr enable -y psss/tmt
            Execute command 'sudo dnf copr enable -y psss/tmt' on guest '10.0.138.247'.
        script: sudo dnf install -y tmt
            Execute command 'sudo dnf install -y tmt' on guest '10.0.138.247'.
        summary: 1 preparation applied
        status: done

Debug level two:

    prepare
        workdir: /var/tmp/tmt/run-448/plans/helps/prepare
        how: shell
        script: sudo dnf install -y 'dnf-command(copr)'
            Execute command 'sudo dnf install -y 'dnf-command(copr)'' on guest '10.0.138.247'.
            Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/psss/.ssh/1minutetip_rsa root@10.0.138.247 sudo dnf install -y 'dnf-command(copr)''.
        script: sudo dnf copr enable -y psss/tmt
            Execute command 'sudo dnf copr enable -y psss/tmt' on guest '10.0.138.247'.
            Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/psss/.ssh/1minutetip_rsa root@10.0.138.247 sudo dnf copr enable -y psss/tmt'.
        script: sudo dnf install -y tmt
            Execute command 'sudo dnf install -y tmt' on guest '10.0.138.247'.
            Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/psss/.ssh/1minutetip_rsa root@10.0.138.247 sudo dnf install -y tmt'.
        summary: 1 preparation applied
        status: done
        Write file '/var/tmp/tmt/run-448/plans/helps/prepare/step.yaml'.

And finally debug level three:

    prepare
        workdir: /var/tmp/tmt/run-449/plans/helps/prepare
        how: shell
        script: sudo dnf install -y 'dnf-command(copr)'
            Execute command 'sudo dnf install -y 'dnf-command(copr)'' on guest '10.0.138.247'.
            Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/psss/.ssh/1minutetip_rsa root@10.0.138.247 sudo dnf install -y 'dnf-command(copr)''.
            err: Warning: Permanently added '10.0.138.247' (ECDSA) to the list of known hosts.
            out: Last metadata expiration check: 0:01:35 ago on St 22. dubna 2020, 04:11:15 EDT.
            out: Package dnf-plugins-core-4.0.13-1.fc31.noarch is already installed.
            out: Dependencies resolved.
            out: Nothing to do.
            out: Complete!
        script: sudo dnf copr enable -y psss/tmt
            Execute command 'sudo dnf copr enable -y psss/tmt' on guest '10.0.138.247'.
            Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/psss/.ssh/1minutetip_rsa root@10.0.138.247 sudo dnf copr enable -y psss/tmt'.
            err: Warning: Permanently added '10.0.138.247' (ECDSA) to the list of known hosts.
            out: Repository successfully enabled.
        script: sudo dnf install -y tmt
            Execute command 'sudo dnf install -y tmt' on guest '10.0.138.247'.
            Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/psss/.ssh/1minutetip_rsa root@10.0.138.247 sudo dnf install -y tmt'.
            err: Warning: Permanently added '10.0.138.247' (ECDSA) to the list of known hosts.
            out: Copr repo for tmt owned by psss                  25 kB/s | 3.3 kB     00:00
            out: Package tmt-0.14-3.fc31.noarch is already installed.
            out: Dependencies resolved.
            out: Nothing to do.
            out: Complete!
        summary: 1 preparation applied
        status: done
        Write file '/var/tmp/tmt/run-449/plans/helps/prepare/step.yaml'.

Does it look ok to you?

**Comment by lukaszachy** [comment]
Thank you. 
For Debug it looks great, but I think it is too verbose by default

By default (no verbose)
```
prepare
    how: shell
    summary: 1 preparation applied
```

Verbose level 1:
```
prepare
    how: shell
    script: sudo dnf install -y 'dnf-command(copr)'
    script: sudo dnf copr enable -y psss/tmt
    script: sudo dnf install -y tmt
    summary: 1 preparation applied
```

**Comment by psss** [comment]
Good, point! Thanks, will adjust.
