### ISSUE TITLE
Nitrate ID error during tmt test export --nitrate

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#217]
Hi,
I am seeing an odd error while exporting fmf converted test back to nitrate.
The test has been exported once before I am exporting it again to test new features.
The output says:
$ tmt test export --nitrate
Test case 'TC#0499983' found.
...
...
Test case 'TC#0499983' successfully exported to nitrate.
ERROR  Nitrate test case id not found.

But I can clearly see that the ID is 0499983 and the data was actually exported into TCMS. I changed tags in main.fmf and those were added to the TCMS test case by the export. So I do not know what the error means.

**Comment by hegerj** [comment]
If you want to export just 'TC#0499983' you need to be in the directory of that test and call `tmt test export --nitrate .` or call it specifically for that test case `tmt test export --nitrate /Regression/bz1182987-RFE-lftp-restricting-each-SSL-TLS-version` from whereever in the gfmf tree.

Right now you are trying to export every test in the fmf tree. Next test tmt is trying to export is `bz1228484-mirror-directory-hang` which was apparently imported before attribute `tcms` was renamed to `extra-nitrate` which is expected.

I recommend to re-import all test cases imported before the change.

**Comment by Athwale** [comment]
I see now, I forgot the "." at the end of the command. Not a bug then.

**Comment by hegerj** [comment]
I forgot about it as well, had to try it myself :)
Closing the issue.
