### ISSUE TITLE
Stop after discover: 0 tests selected

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#246]
Shouldn't be `0 tests selected` from 'discover' step a show stopper?

Further steps should cope with that though, if one wants to skip discovery and run plan just for provision/prepare.

Say I want to run test (`run tests --name`), it is quite reasonable that such test doesn't need to be in all plans. But pipeline continues and fails after provision and prepare. Those steps are time/resource consuming and that error is a false negative, IMHO.

In tmt repo, `tmt run -a tests --name /tests/discover/filtering prepare --how shell -s 'echo 1' report -vv`
```
/plans/basic
    discover
       summary: 1 test selected
 --- cut %< ---
      summary: 1 test passed

/plans/helps
    discover
        summary: 0 tests selected
 --- cut %< ---
    execute
        how: shell
    finish
        summary: 0 tasks completed
 ERROR  Test execution failed: ("Failed to run command './run.sh -v .. shell stdout.log stderr.log'.", './run.sh -v .. shell stdout.log stderr.log', '', '')
```

**Comment by psss** [comment]
Agreed. I'd say, if no tests are discovered, following steps should be skipped. If at least one test has been executed (from all plans) then exit code should be `0`, otherwise probably `3` as "something went wrong". We should document exit codes somewhere. Will create a pull request for that.
