### ISSUE TITLE
tmt plan lint returns 0 even if a fail is discovered

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#259]
I noticed that when tmt plan lint finds a fail it still returns 0 exit code.

[me@localhost]$ cat ci.fmf 
summary: Basic smoke test
discover:
    name: CoreOS
    how: fmf
    filter: 'tier: 1'
    repository: git:....
execute:

[me@localhost]$ tmt plan lint
/ci
fail execute step must be defined
[mek@localhost]$ echo $?
0

A fail is probably something that should prevent you from using such plan if you are using the linter in a script to automate the process.

**Comment by psss** [comment]
@FrNecas, would you like to have a look at this?

**Comment by FrNecas** [comment]
@psss sorry, I completely forgot about this one. Will take a look at it now
