### ISSUE TITLE
Document / simplify iterative test development

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#285]
Use case: As a tester I want to edit and re-run test until I am satisfied with the result

So tmt need to 
1. sync changes in the test 
2. run test 
3. report new result

If tmt wants to be really user friendly it could watch for changes and rerun on each save.

With current state it is doable but requires a bit of typing.
1. `tmt run --until report tests --name . report -vv`
2. edit tests
3. `tmt run --last discover -f execute -f report -vv -f`

**Comment by psss** [comment]
Yeah, this common use case should be as simple as possible. We need to improve this.

**Comment by psss** [comment]
As a first step I've documented an initial set of aliases which can be useful for test debugging in #404.

**Comment by psss** [comment]
Documentation covered by the new [Aliases](https://tmt.readthedocs.io/en/latest/examples.html#aliases) section. @lukaszachy, is that a sufficient fix for now or would you like to keep this issue open until we have a better solution without aliases?

**Comment by psss** [comment]
Support for native tmt aliases will be tracked in #414. Closing this one.
