### ISSUE TITLE
`run ---force` is is too eager to delete workdir

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#286]
There is fatal difference between 
`tmt run --last  -f discover execute report` and 
`tmt run --last discover -f execute -f report -f`

Use case: As a user I want to save typing, so if all steps need to run in `--force`, similarly to verbose or debug levels, I want to write it once for the whole run.
Use case: As a tester I changed my test and I want re-run it on already provisioned and prepared guests. 

However the first, shorter, command deletes the workdir so when user realises their mistake the workdir is lost together with its guest.yml. 
So instead of test rerun they end up with ` ERROR  No guests available for execution.` and in addition to the lost time for re-provision user needs to clean guests as well

**Comment by FrNecas** [comment]
Should be simple to fix, I will take this one. As agreed on the hacking session, let's make `tmt run -f` behave similarly to the rest of the flags (just inherit) and add new option `--scratch` that does what `tmt run -f` used to do
