### ISSUE TITLE
Report `fail` in `tmt lint` for empty environment files

### ISSUE THREAD

**Issue by bgoncalv** [psss/tmt#2872]
In our repo we have a lot of tests that when running tmt lint shows `warn: Empty environment file`

It would be nice if we could force tmt lint to report failure in this cases, afaik it is not handled as a warning class.

My suggestion would be running a command like below would force the lint to report failure.

```
tmt lint --outcome-only fail --enforce-check Cxxx .
```

**Comment by psss** [comment]
For this specific case, when `environment-file` is pointing to an empty file, I would say we should even give a failure by default. Could be a good first issue, here's an example plan check:

https://github.com/teemtee/tmt/blob/22731b9761b62177de00ee7818c2f0ee4efcfe03/tmt/base.py#L2027-L2039

**Comment by mcasquer** [comment]
@psss @happz I guess we can close this issue as the PR has been merged right?
