### ISSUE TITLE
tmt plan create plan.fmf creates incorrect double .fmf.fmf filename

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#298]
Using tmt plan create plan.fmf --template mini results in:
Plan '/home/me/Priprava/plan.fmf.fmf' created.
The plan name plan.fmf.fmf is wrong.

I am used to proving full file names including the suffix and this is a little confusing.
I would suggest checking whether the suffix is provided by the user and in such case create a correct file and if it is not, then append the suffix as was the previous behaviour.

**Comment by psss** [comment]
Yes, that makes sense. The same applies for `tmt story create` and (just to be sure) for `tmt test create`.
