### ISSUE TITLE
braindump of suggestions

### ISSUE THREAD

**Issue by thrix** [psss/tmt#3]
I like what the tool currently implements. It is basically a listing of test metadata. It is very handy, as it shows the parsed state for all test sets. I think we should keep this functionality under a new subcommand though - ```ls```.

tmt ls
-------
This command would show the listing of the tests.

```
$ cd examples/systemd
$ tmt ls
Found 2 testsets.

Testset: /ci/pull-request/functional (Tier two functional tests)
Discover:
{'filter': 'tier: 2 & distros: rhel-8',
 'how': 'fmf',
 'repository': 'https://github.com/systemd-rhel/tests'}
Provision:
{'how': 'vm'}
Prepare:
{'how': 'ansible', 'playbooks': ['ci/rhel-8.yml']}
Execute:
{'how': 'beakerlib'}
Report:
None
Finish:
None

Testset: /ci/pull-request/smoke (Basic set of quick smoke tests for systemd)
Discover:
{'filter': 'tier: 1 & distros: rhel-8',
 'how': 'fmf',
 'repository': 'https://github.com/systemd-rhel/tests'}
Provision:
{'how': 'vm'}
Prepare:
{'how': 'ansible', 'playbooks': ['ci/rhel-8.yml']}
Execute:
{'how': 'beakerlib'}
Report:
None
Finish:
None
```
And display only one test by specifying it.

```
$ tmt ls /ci/pull-request/functional 
Testset: /ci/pull-request/functional (Tier two functional tests)
Discover:
{'filter': 'tier: 2 & distros: rhel-8',
 'how': 'fmf',
 'repository': 'https://github.com/systemd-rhel/tests'}
Provision:
{'how': 'container'}
Prepare:
{'how': 'ansible', 'playbooks': ['ci/rhel-8.yml']}
Execute:
{'how': 'beakerlib'}
Report:
None
Finish:
None
```

tmt run
---------
The ```run``` command would be executing the tests sequentially for now. As we have in our flock prototype. I would like thought, if the runner from the start would be container based, so we would have easier path forward to change the implementation later on to something more robust and unified with the testing system itself. This would also keep ```tmt``` minimal, the only thing we would need to add as a dep is podman.

```
$ cd examples/systemd
$ tmt run
Pulling container of worker quay.io/testing-farm/cruncher ...
Running test: /ci/pull-request/functional
[17:25:13] [+] [cruncher] Downloading image 'Fedora-Cloud-Base-30-20190906.0.x86_64.qcow2'
[17:26:13] [+] [cruncher] Booting VM with image 'Fedora-Cloud-Base-30-20190906.0.x86_64.qcow2'
[17:26:34] [+] [cruncher] [/ci/test/build/smoke] [execute] Running shell commands
# dnf -y install httpd curl
....
```

Thinking about renaming the tool
--------------------------------------------
Also in the future we might want to add additional features, like reproducing a test that was run via Packit, Fedora CI or in RHEL. This will bend this tool to be more a command line tool of the test system itself. Not sure yet about this, but I think it would make sense to have just one tool for all these interactions.

**Comment by psss** [comment]
Thanks for the feedback. Good idea to separate listing info and executing tests. What about introducing a `testset` subcommand which could cover metadata investigation but could be also combined with test execution? It could look like this:

List available testsets:

    tmt testset --list

Include gathered details about individual test steps in the output (basically what the tool does now):

    tmt testset --list --steps
    or
    tmt testset --list --verbose

Filter available test sets:

    tmt testset --list --filter REGEXP

Use together with test execution (e.g. select only test sets relevant for pull requests):

    tmt testset --filter ^/ci/test/pull-request
    tmt prepare execute testset --filter ^/ci/test/pull-request

I think the test execution should be the primary use case for the command line so I'd suggest to make the syntax for that super-short (preferrably without the extra `run` command).

    tmt
    tmt execute
    tmt prepare execute
    tmt provision prepare execute

What do you think?

**Comment by psss** [comment]
Regarding the `podman` dependency and containerized runner: Agreed to have the support from the start but I'd propose to enable super-minimal-dependencies as well, meaning for those use cases when you just want to execute tests on a prepared vm/localhost without fetching any container/distro images.

**Comment by thrix** [comment]
@psss in regards to the first comment, it would also solve the situation :)

In regards to second, this will mean that we will need to add additional rpm dependencies to tmt, like ansible (for ```how: ansible```), standard-test-roles (for ```how: sti```, once we use it), beakerlib (for how: beakerlib) etc :) By using a container this can be avoided. But I get your idea. The only thing that bugs me  is how to solve both use cases without implementing the same functionality in the runner and in tmt

**Comment by thrix** [comment]
If we could make tmt a library, that the runner could use, that would be the best

**Comment by thrix** [comment]
So we do not have a duplicate functionality. That would mean abstracting away the command run (in case of localhost it would run directly commands on localhost, in case of the runner remotly via ssh). What do you think @psss? Also it would make sense to speak about this with @happz if there is no issue moving this forward like this,

**Comment by thrix** [comment]
Maybe the problem with the various dependencies we could just simply solve by having the various backends as subpackages in the future (tmt, tmt-sti, tmt-beakerlib, etc.)

**Comment by thrix** [comment]
@psss and also ... so for interaction with the CI systems runs we will have another tool? that is what you are suggesting?

**Comment by psss** [comment]
Yeah, I like very much the idea of a common library. The major functionality should be implemented in the python module, the command line interface should be very simple/basic/dumb. If there si need for extra requirements I would agree the subpackage approach could be a nice way. That would allow minimal installation of `python3-tmt` for integration with CI, `tmt` for simple command line with only basic test execution on localhost and additional plugins such as `tmt-sti` or `tmt-beakerlib` for more.

**Comment by psss** [comment]
I believe we've covered raised questions in the comment above and in person. Closing. Feel free to reopen if anything essential still needs to be addressed.
