### ISSUE TITLE
FYI: container images

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#305]
I've created tmt-all images:

https://github.com/pvalena/tmt-all/

https://hub.docker.com/r/pvalena/fedora-tmt-all/tags

Maybe this could be part of fedora registry?

I find them quite useful, see [my example](https://gist.github.com/pvalena/465cd708e55bc4a5982ac2dda4939786).

I look forward to your suggestions. (I know that without the mount it currently is broken, I'll fix that later on.)

**Comment by pvalena** [comment]
@psss @thrix  WDYT?

Here're the 2 missing plans- basic (succeds), install (fails; needs virtualization/containerization):

https://gist.github.com/pvalena/0ac019aecbb1bcf9df77f248e71cad72

**Comment by thrix** [comment]
pretty neat @pvalena ! :) I like the idea of having images like these. If we could make the official moving forward, it woudl be pretty awesome. I have no idea who to contact in those regards, if that is even an option.

**Comment by psss** [comment]
Nice idea! Could be handy. What would be the best place for the `tmt` container images?

* https://registry.fedoraproject.org/
* https://registry.centos.org/containers
* https://quay.io/

Or any other place?

**Comment by lukaszachy** [comment]
docker.io as it is present in configuration on Fedora, RHEL and CentOS.

**Comment by psss** [comment]
So `docker.io` is https://hub.docker.com/, right? Shall we create a new `tmt` account there to be able to do `podman pull tmt/all` or `podman pull tmt/core` and similar? Is it possible to configure docker hub repo/account so that the shortest command `podman pull tmt` is possible as well?

**Comment by pvalena** [comment]
> So `docker.io` is https://hub.docker.com/, right? Shall we create a new `tmt` account there to be able to do `podman pull tmt/all` or `podman pull tmt/core` and similar? Is it possible to configure docker hub repo/account so that the shortest command `podman pull tmt` is possible as well?

I vote for Fedoras' https://registry.fedoraproject.org/ , as it builds nicely from Fedora content ([example](https://src.fedoraproject.org/container/ruby/tree/master)), but AFAIK there are not automated rebuilds (with new versions).

**Comment by pvalena** [comment]
We have container images on `quay.io`.

**Comment by psss** [comment]
For reference, the links are:

* https://quay.io/repository/testing-farm/tmt
* https://quay.io/repository/testing-farm/tmt-all
