### ISSUE TITLE
Consider doing `Guest.details()` in more generic way

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#310]
What about `/etc/os-release` ? I's IMO more generic.

But it's not completely same:
```
# What you'd probably want
PRETTY_NAME="Fedora 31.20200703.0 (Workstation Edition)"

# Currently is
Fedora release 31 (Thirty One)
```

_Originally posted by @pvalena in https://github.com/psss/tmt/pull/307_

**Comment by pvalena** [comment]
Someone has made a comparison already: https://gist.github.com/natefoo/814c5bf936922dad97ff

**Comment by pvalena** [comment]
Note: the rest (not using `/etc/os-release` like CentOS 6) use `/etc/lsb-release`.

**Comment by psss** [comment]
It seems on RHEL6 / CentOS 6 there are only the following release files available:

    /etc/centos-release
    /etc/redhat-release -> centos-release
    /etc/system-release -> centos-release
    /etc/system-release-cpe

So we will have to fallback to `/etc/redhat-release` anyway.

**Comment by pvalena** [comment]
@psss are you sure there's no `/etc/lsb-release`?

**Comment by psss** [comment]
You have to install `redhat-lsb-core` which is not installed by default. Yes, `/etc/system-release` can be the last resort.
