### ISSUE TITLE
`login` does not run in some cases

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#323]
How to reproduce:
```
$ tmt run  --skip finish 
$ tmt run -l login
```

Example run: https://gist.github.com/pvalena/99231950099a81a8aef83329a0d8a643

_ _ _ _

Can be worked around using something like `tmt run -l login report -f` ([example](https://gist.github.com/09bde136e0acac0fcf25a2729fd0cf99)).

**Comment by psss** [comment]
Yes, the `login` step should always be activated, even if the step during which it is supposed to be run, has been already done.

**Comment by psss** [comment]
This might be a duplicate of #284.

**Comment by pvalena** [comment]
Yes it's a duplicate. Thanks!
