### ISSUE TITLE
support excluding specific artifacts from prepare phase

### ISSUE THREAD

**Issue by todoleza** [psss/tmt#33]
For some components not all artefacts are really needed and could break test environment preparation or needlessly prolong it, namely graphical packages for daemons like firewalld.
In (probably) prepare phase I'd like to set a list of white/black list wild cards for artefact name that should not/be part of installed SUT.

**Comment by pvalena** [comment]
Makes sense.
@psss how is filtering handled elsewhere? On `Prepare` level or before the `data[*]` gets there?

**Comment by psss** [comment]
This has been covered by the `exclude` key in [prepare install](https://tmt.readthedocs.io/en/latest/spec/plans.html#install) plugin.
