### ISSUE TITLE
Detached executor does not work with the CentOS 6 container

### ISSUE THREAD

**Issue by psss** [psss/tmt#339]
Test `/tests/prepare/install` fails when run against rpm-packaged `tmt`:

    sh: ./run.sh: /usr/bin/bash: bad interpreter: No such file or directory
    Error: exec session exited with non-zero exit code 126: OCI runtime error

This is caused by `/usr/bin/bash` in the `run.sh` script shebang. Seems to be substituted during rpm packaging (the source file has `/bin/bash` which would work. The `shell.tmt` method works fine.

**Comment by martinky82** [comment]
The problem is most likely caused by:
https://pagure.io/packaging-committee/issue/738

and should be fixable:
It is now possible to disable this BRP by unsetting %__brp_mangle_shebangs or setting it to /usr/bin/true.

**Comment by martinky82** [comment]
https://github.com/psss/tmt/pull/341
