### ISSUE TITLE
When test references beakerlib library tmt run always asks for github credentials

### ISSUE THREAD

**Issue by matusmarhefka** [psss/tmt#340]
When running a test using `tmt run -a provision -h minute ...` and the test references some beakerlib library which is not under https://github.com/beakerlib/ `tmt` asks for github credentials. This might be because it does not find a public repo for the beakerlib library and it tries to check if the repo is not private. The credentials are requested through a pop-up window which blocks execution and looks like this:

![Screenshot from 2020-09-08 10-32-06](https://user-images.githubusercontent.com/3180425/92452906-ef5ab180-f1be-11ea-9757-b224356deec0.png)

**Comment by psss** [comment]
Seems we could use one of the following options to disable the interactive prompt:

```
git clone -c core.askPass $echo https://github.com/beakerlib/missing
git clone -c core.askPass https://github.com/beakerlib/missing
GIT_ASKPASS=echo git clone https://github.com/beakerlib/missing
```

**Comment by psss** [comment]
@matusmarhefka, for reference, could you please share the version of `git` you are using? Thanks.

**Comment by matusmarhefka** [comment]
> @matusmarhefka, for reference, could you please share the version of `git` you are using? Thanks.
```
$ git --version
git version 2.26.2
$ rpm -q git
git-2.26.2-1.fc32.x86_64
```
