### ISSUE TITLE
add switch `-c|--console` to passthrough the console output not only in -vvv

### ISSUE THREAD

**Issue by sopos** [psss/tmt#353]
It is really useful for manual execution to see the actual console output as the test runs. It helps to debug timing issues, etc.
It might be also useful to see console output of other stages like `prepare` as one can see what is taking sooo much time.
Actually It might be useful to passthrough full output, not only complete lines, e.g. including progress bars.

**Comment by sopos** [comment]
`execute --how beakerlib` actually does not print the console output during the run at all. It print all the output at the end

**Comment by psss** [comment]
The complete output can be enabled by turning on debugging. So using `-vvvddd` should cover your use case. This applies for all steps. Is there anything else you're still missing?

**Comment by sopos** [comment]
So far I'm ok with -vvvddd. For normal usecases it works . Let's close this issue and possibly reopen if the necessity appears again.
