### ISSUE TITLE
detached or non-detached execution should be controled by a switch

### ISSUE THREAD

**Issue by sopos** [psss/tmt#360]
to choose from detached or non-detached run should not be done by choosing different execution method but by the command line / test plan switch

Imagine the situation where the execute type is set in L1. One could want to run the test while seeing the console output in real-time while executing it by an automation might want to use detached regime. The execution type should be e.g. beakerlib for both cases but handled differently in different situations.

**Comment by psss** [comment]
So the plan with #302 is to completely move the `framework` selection to `L1` metadata (with some backward compatibility handling to prevent regressions with the old configs) which should result into what, I believe, is your described scenario. You select on the commandline or in the plan which executor should be used. Pipeline would have some default. You can override from the command line as needed and you can specify it in the plan as well.

**Comment by psss** [comment]
I believe this has been covered by #302. Feel free to reopen if not.
