### ISSUE TITLE
Import of test case metadata from Nitrate is incomplete

### ISSUE THREAD

**Issue by tomato42** [psss/tmt#379]
When importing test cases from Nitrate many fields are skipped, like Notes, Setup, Actions, Breakdown or Expected Results.

That means that if the Notes field includes information why some environments are skipped in relevancy, or the Setup includes information about need for special hardware to run the test, that information is lost on import.

Please include the contents of those fields in the description field in fmf.

**Comment by hegerj** [comment]
@psss it seems there is more interest in importing Setup/Actions/Breakdown/Exp. for automated tests.
Previously we agreed that there will be "best effort" approach for import these fields for automated tests, as it may generate many new files, cluttering the test directory. It was decided that just one file will be created per test (as opposed to one file per nitrate testcase).
Shall we reconsider?

**Comment by psss** [comment]
The limitation was related to virtual cases (e.g. multiple nitrate cases for a single beaker task). And I still think this will be rather a corner case. On the other hand importing the content of the `notes` field into `description` does not collide with anything.

@tomato42, regarding manual test fields: We import them into a separate file `test.md` in markdown format. So for now it works only with `--manual` but in #362 there is work in progress to enable it also for for automated. See also the [manual](https://tmt.readthedocs.io/en/latest/spec/tests.html#manual) attribute definition.

**Comment by tomato42** [comment]
I'm ok with Setup/Actions/Breakdown/Exp. imported to a new `test.md` file.

**Comment by psss** [comment]
Good. Then let's append `header` and `footer` from the test case notes StructuredField into the description.

**Comment by psss** [comment]
Fixed by #468.
