### ISSUE TITLE
Prepare step should be able to run before artifact installation and after artifact installation

### ISSUE THREAD

**Issue by thrix** [psss/tmt#39]
While trying to fix #26 I found out that I am out of luck. The fix is to include epel-release before installing the artifact but we have no way to do that now. It is questionable how to do it. We can mark parts of prepare to be before artifact installation or have a separate section, or maybe even put it in the already planned artifact step ....

@psss @leospol @pvalena @happz what do you think?

**Comment by happz** [comment]
+1. We discovered the need to split `prepare` step into several stages in the real world, the specification should support us in doing so. In our internal workflow, we had to introduce `pre-artifact-installation` and `post-artifact-installation` steps, "wrapping" the actual installation of the artifact, all three part of the `prepare` step. Users should be able to specify whether they want to install a package/enable repository/run playbook/etc. *before* the installation of the artifact, or *after*, or even signal they don't care at all when this action would take the place, e.g. by not specifying any such requirement.

**Comment by pvalena** [comment]
Shouldn't all of this be handled by prepare?

In general I agree, prepare should have some sub-items / sub-steps. But doesn't it have already? Because the 'how' comes as a list of instructions, so it should be possible to use it as a ordered list, having an some specific entry as an artifact install? _(If not present, it would run last.)_

Please see https://github.com/psss/tmt/pull/30/commits/d46317ba47faf88726a72050821d10e2cce4894a from #30.

**Comment by psss** [comment]
I believe the use case could/should be covered by the `order` attribute which has been introduced during conversion into dynamic plugins. Each steps can have serveral configs and each of them can have a dedicated `order`. This allows users to select when/where exactly the config should happen.

```
Usage: tmt run prepare [OPTIONS]

  Prepare the environment for testing

  Use the 'order' attribute to select in which order preparation should
  happen if there are multiple configs. Default order is 50. Default order
  of required packages installation is 70.

  Supported methods (shell by default):

  ansible .............. Prepare guest using ansible
  install .............. Install packages on the guest
  shell ................ Prepare guest using shell scripts

  Use 'tmt run prepare --help --how <method>' to learn more about given
  prepare method and all its supported options.
```

**Comment by lukaszachy** [comment]
As far as I know `order` attribute is working correctly in [prepare](https://tmt.readthedocs.io/en/stable/spec/plans.html#prepare) step.
Please reopen if you need more functionality

**Comment by psss** [comment]
I'm afraid the missing part is that testing farm would perform the artifact installation under a specific `prepare` order. I imagine this could work something like this:

    tmt run --all provision ... prepare --how install --directory /path/to/rpms --insert --order=AGREED_ORDER

Users then would be able to specify prepare steps configuration for both before and after the artifact installation. But this means that `tmt` would have to be taught how to (properly) do the artifact installation.
