### ISSUE TITLE
From the docs, it is not clear what "steps" actually do

### ISSUE THREAD

**Issue by hroncok** [psss/tmt#4]
In the documentation, there are several steps described. I'll use this issue to describe the confusion I have:

> **discover**: gather info about test cases to be run

I assume this tep will inform the user about the tests that can be run, correct? If so, maybe describe it as: ***lists** info about test cases to be run*.

> **provision**: what environment is needed for testing, how it should provisioned

What does this do? Does it provision the environment, or does it tell me what environment I need to prepare myself? Will it start potentially dangerous actions, like installing software to my workstation or talking to some service?

> **prepare**: additional configuration needed for testing (e.g. ansible playbook)

What does this do? Does it run ansible in the previously provisioned thing? Or does it run ansible on my workstation?

> **execute**: test execution itself (e.g. framework and its settings)

Does this execute the tests? Where? How?

> **report**: adjusting notifications about the test progress and results

Adjusting? How?

> **finish**: actions to be performed after the test execution has been completed

Huh? Are the actions performed when I run this command, or?

**Comment by psss** [comment]
> In the documentation, there are several steps described. I'll use this issue to describe the confusion I have:

For the start I just included list of steps planned to be supported. See the [L2 Metadata](https://pagure.io/fedora-ci/metadata/blob/master/f/l2) spec for detailed description of individual steps. I see this might be confusing. We should probably add a TODO tags there.

> > **discover**: gather info about test cases to be run
> 
> I assume this tep will inform the user about the tests that can be run, correct? If so, maybe describe it as: _**lists** info about test cases to be run_.

Yes, this steps does test discovery and shows what would/will be tested. I'll improve the wording.

> > **provision**: what environment is needed for testing, how it should provisioned
> 
> What does this do? Does it provision the environment, or does it tell me what environment I need to prepare myself? Will it start potentially dangerous actions, like installing software to my workstation or talking to some service?

For each step there will be several implementations possible, for provision we plan something like this:

    localhost ... run directly on the local machine
    openstack ... create vm in using OpenStack
    beaker ... reserve machine using Beaker
    podman ... create a container using podman
    qemu-kvm ... run a vm using qemu-kvm

Here comes the concept of DDD (default, detect, defined). We would like to have a reasonable `default` which could be optionally influenced by a `detect` action (e.g. could be arch detection from the rpm package) and manually overriden by manual `define` in config or on the command line.

    tmt                             # would run the default provision (or the one configured in ci.fmf)
    tmt provision --how beaker      # reserve a machine in Beaker (override default/config)

Does that make sense to you?

> > **prepare**: additional configuration needed for testing (e.g. ansible playbook)
> 
> What does this do? Does it run ansible in the previously provisioned thing? Or does it run ansible on my workstation?

Preparation would be applied on the provisioned box. This step depends on the result of the `provision` step.

> > **execute**: test execution itself (e.g. framework and its settings)
> 
> Does this execute the tests? Where? How?

On the result of the `provision` step. Could be a beaker machine or localhost... How?

We don't plan that `tmt` would implement all possible executions. Rather it should serve as a nice & consistent interface for the user and redirect the implementation itself for example to `citool` or other.

> > **report**: adjusting notifications about the test progress and results
> 
> Adjusting? How?

For now (see the spec) we've just outlined configuring a custom email address or irc channel.

> > **finish**: actions to be performed after the test execution has been completed
> 
> Huh? Are the actions performed when I run this command, or?

Yes, by default all six steps would be executed. But this is an optional step and thus can be omitted from the config.

Thanks for great questions! Hope this clarifies it a bit more. We definitely need to have a good and clear documentation for users. I think the best way will be if we extend `tmt` documentation step by step as individual features are being implemented to make the clear distintion between spec and already supported stuff.

**Comment by hroncok** [comment]
Thanks, it makes a it a bit better, but the docs are not describing the commands, they are describng a workflow. I don't understand why as an user I control the flow by commands. What happens if I just run `tmt finish` without running `tmt provision` and `tmt execute`? Why doesn't `provision` happen automatically when I run `execute`?

**Comment by psss** [comment]
The intention is to give users flexibility to select individual steps which are relevant for their current use case. See for example these scenarios:

Do not execute anything, just let me see which tests will be executed:

    tmt discover

I have everything prepared and installed on my vm where I am playing with the latest bits. Please, just run my tests now:

    tmt discover execute

It would probably make sense to have `discover` as a dependency of `execute` so that we can only run (not sure yet):

    tmt execute

I have reserved my machine from Beaker as I need some extra stuff. Just apply the playbooks and any other prepare stuff to have it configured and run tests:

    tmt prepare execute

Oh, I see the problem. Fixed. Now just rerun tests again. No need to re-run the long list of ansible tasks again:

    tmt execute

The examples above are showing use cases when `tmt` is run directly from the system under test. But we want to support different test runner as well:

    tmt discover provision --how openstack prepare execute

Which would take a vm from openstack, prepare it and execute tests there. But all of this could be stored in the config so ideally you would just need to run:

    tmt

We could also possibly support something like this:

    tmt provision --how openstack --keep
    tmt execute
    vim runtest.sh
    tmt execute
    vim runtest.sh
    tmt execute
    tmt provision --drop

This could make test debugging faster instead of again and again provisioning and configuring a new vm. What do you think?

**Comment by hroncok** [comment]
I see. Thanks for explaining. I'd hoped for something less complicated :face_with_head_bandage: 

This is the API I was hoping for:

```
$ tmt --mock fedora-31-x86_64 --no-clean --enable-network --enablerepo=updates-testing
$ tmt --docker fedora:rawhide --cap-add=SYS_ADMIN
```

But arguably, some test are more complex than others.

**Comment by psss** [comment]
I see. Thanks for the feedback. The proposed syntax is just an outline/draft. Let's work together to find the most efficient / flexible approach. I've filed #5 for the mock use case and #6 for the container use case.
