### ISSUE TITLE
check provides instead of packages by rpm

### ISSUE THREAD

**Issue by sopos** [psss/tmt#401]
Currently, the not satisfied requirements are installed during the prepare step. Before the actual dnf call, there is acheck for the presence of the packages. In case the requirement is referenced by a _provides string_ and not the _package name_, the `rpm -q` fails on that provide. `rpm -q --whatprovides` should cover this case.

```
# rpm -q "rpm" "library(distribution/dpcommon)" "curl" "beakerlib"; echo $?
rpm-4.14.3-4.el8.x86_64
package library(distribution/dpcommon) is not installed
curl-7.61.1-14.el8.x86_64
beakerlib-1.18-12.el8bkr.noarch
1
# rpm -q --whatprovides "rpm" "library(distribution/dpcommon)" "curl" "beakerlib"; echo $?
rpm-4.14.3-4.el8.x86_64
distribution-distribution-Library-dpcommon-1.0-27.noarch
curl-7.61.1-14.el8.x86_64
beakerlib-1.18-12.el8bkr.noarch
0
```

To support the requirement referenced by a full path to a file (which is correct for dnf/yum) and additional check `rpm -qf` could be involved.

**Comment by pvalena** [comment]
Wouldn't all of that be solved by simply calling `dnf` wihout rpm checks? Originaly introduced as a speedup, but as `dnf` is nowdays fast enough for subsequent runs, does it make sense to do multiple rpm calls prior to actual running `$ dnf install` once? (The `dnf`-subsequent speedup is only in case `dnf` has to run / will run to install some other dependencies.) From my experience the `dnf install` runs anyway, so why add additional handling / code complexity?

**Comment by sopos** [comment]
Yes, I take this rpm as a speed up. It may still speed the things up pretty much as dnf at least needs to download metadata or check their freshness.
According to my observations it is better to avoid `dnf` calls wherever possible. But yes, `dnf` should be enough.

**Comment by thrix** [comment]
> Currently, the not satisfied requirements are installed during the prepare step. Before the actual dnf call, there is acheck for the presence of the packages. In case the requirement is referenced by a _provides string_ and not the _package name_, the `rpm -q` fails on that provide. `rpm -q --whatprovides` should cover this case.
> 
> ```
> # rpm -q --whatprovides "rpm" "library(distribution/dpcommon1)" "curl" "beakerlib"; echo $?

is the `--whatprovides` here by an error in this example? :)

> rpm-4.14.3-4.el8.x86_64
> no package provides library(distribution/dpcommon1)
> curl-7.61.1-14.el8.x86_64
> beakerlib-1.18-12.el8bkr.noarch
> 1
> # rpm -q --whatprovides "rpm" "library(distribution/dpcommon)" "curl" "beakerlib"; echo $?
> rpm-4.14.3-4.el8.x86_64
> distribution-distribution-Library-dpcommon-1.0-27.noarch
> curl-7.61.1-14.el8.x86_64
> beakerlib-1.18-12.el8bkr.noarch
> 0
> ```
> 
> To support the requirement referenced by a full path to a file (which is correct for dnf/yum) and additional check `rpm -qf` could be involved.

**Comment by sopos** [comment]
yes, you're right, I accidentaly copy&pasted wrong command, I meant
```
# rpm -q "rpm" "library(distribution/dpcommon)" "curl" "beakerlib"; echo $?
rpm-4.14.3-4.el8.x86_64
package library(distribution/dpcommon) is not installed
curl-7.61.1-14.el8.x86_64
beakerlib-1.18-12.el8bkr.noarch
1
```

**Comment by pvalena** [comment]
> Yes, I take this rpm as a speed up. It may still speed the things up pretty much as dnf at least needs to download metadata or check their freshness.

This may not be true, as the subsequent runs recognize (in Fedora) it was checked for some recently, and uses the cached version (there's some invalidation timeout). [Example](https://gist.github.com/pvalena/ec1ab0841612bdfe476a6367ab626daa).

> According to my observations it is better to avoid `dnf` calls wherever possible. But yes, `dnf` should be enough.

Well, in this case we'd make several calls of `ssh` (we don't keep the shell open; there'll be multiple `$ rpm` calls we need to make, based on this issue). It adds both complexity and time (for the roundtrip, in case of remote machine).

 Is there some other advantage / disadvantage of `$ dnf instal ...`, apart from fetching the metadata?

_ _ _ _

Also if we're so concerned with fetching the metadata, we can run dnf in "cached" mode (`dnf -C install`), for the first call, and if it fails, we can run it without. This however requires the host to have _some_ cache (even outdated one), because it will fail otherwise. [Example](https://gist.github.com/pvalena/b6a0089dc2f6c3f233e7e4650e78bf85).

**Comment by psss** [comment]
Seems that `dnf/yum --cacheonly` nicely covers the `rpm -q` functionality. Only the debug log is a little bit longer. But I can guess we can live with that if it makes things faster. Please review #424.
