### ISSUE TITLE
Symlinks are skipped when syncing with SUT

### ISSUE THREAD

**Issue by sopos** [psss/tmt#402]
During the execute step, there's a sync of the work directory to the SUT using rsync. However not all files are synced there. In particular symbolic links are skipped.
```
            Run command 'rsync -Rrze "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null" --delete /var/tmp/tmt/run-019/plans/default root@10.0.138.116:/'.
            err: Warning: Permanently added '10.0.138.116' (ECDSA) to the list of known hosts.
            out: skipping non-regular file "var/tmp/tmt/run-019/plans/default/discover/default/libs/distribution/epel/lib.sh"
```

I'm experimenting the beakerlib distribution libraries backwards compatibility so I wanted to make it able to use rlImport with the original name. In particular I'm trying to connect distribution/epel [1] with epel/epel [2] library.

1. https://github.com/beakerlib/distribution/tree/master/epel
2. https://github.com/beakerlib/epel/tree/master/epel

**Comment by psss** [comment]
Should be fixed by #413.
