### ISSUE TITLE
Improve "Unsupported method 'virtual'" error message

### ISSUE THREAD

**Issue by voxik** [psss/tmt#405]
Doing my first steps with TMT, this error message is not helpful at all and would deserve clarification:

~~~
$ tmt run
/var/tmp/tmt/run-030

/ci
Unsupported method 'virtual' in '/ci'.
~~~

I am tempted to leave it here without more details, because it is obvious what is going on, right :innocent:

**Comment by voxik** [comment]
~~~
$ rpm -qa tmt*
tmt-1.0-1.fc34.noarch
~~~

Please don't tell me that I should have installed tmt-provision-virtual. Update the error message instead to be helpful instead.

**Comment by voxik** [comment]
Or alternatively use the best method available, e.g. `local`

**Comment by psss** [comment]
Hm, defaulting to `local` could be dangerous... I think we should improve the error message.

**Comment by voxik** [comment]
> Hm, defaulting to `local` could be dangerous... I think we should improve the error message.

But can it pick anything except of the `virtual`, e.g. container?

Also, the `local` is not dangerous per se, because it needs root privileges (right?) and it could display big red warning that there were no better provisioner found, so that is the last, although dangerous option.

**Comment by psss** [comment]
We can discuss if it would make sense to have some kind of a "dynamic" default in the future. I'm not completely sure about it. For now, I've improved the messaging so that it gives some useful hints:

```
> tmt run 
/var/tmp/tmt/run-327

/plans/example
    hint: Install 'tmt-provision-virtual' to run tests in a virtual machine.
    hint: Use the 'local' method to execute tests directly on your localhost.
    hint: See 'tmt run provision --help' for all available provision options.
Unsupported provision method 'virtual' in '/plans/example'.
```

**Comment by psss** [comment]
> Also, the `local` is not dangerous per se, because it needs root privileges (right?)

Yes, that's right. But still, it can do a lot of things in your home ;-) And I remember the unpleasant surprise when `standard-test-roles` defaulted to run on localhost when the vm provisioning was not successful...

**Comment by voxik** [comment]
> ```
> > tmt run 
> /var/tmp/tmt/run-327
> 
> /plans/example
>     hint: Install 'tmt-provision-virtual' to run tests in a virtual machine.
>     hint: Use the 'local' method to execute tests directly on your localhost.
>     hint: See 'tmt run provision --help' for all available provision options.
> Unsupported provision method 'virtual' in '/plans/example'.
> ```

It is better, but still, there is no `virtual` mentioned anywhere in my file, so that is what is confusing about this method. If there was visible where this comes from (e.g. some default template/configuration).

**Comment by psss** [comment]
@voxik, do you suggest that `tmt init` or `tmt plan create` should explicitly include the default provision method when creating new plans? That would work fine. Except for the `mini` template which should be really minimal.

**Comment by voxik** [comment]
I got template from PR, so I am not sure that modifying `tmt init` or `tmt plan create` would help, if somebody deleted the statement.

**Comment by voxik** [comment]
If there was obvious the step from my `ci.fmf` to some `fullyexpandedtemplatedusedtorunthetest.fmf`, that is what would help.

**Comment by psss** [comment]
Hmmm, perhaps `tmt plan show -v` could help here? It shows the default values for each step as well.

**Comment by voxik** [comment]
But I am looking for good UX. It is nice that there is command such as `tmt plan show -v` but the learning curve should not be that steep. I don't want to become expert on tmt, I just want to try the PR.

**Comment by psss** [comment]
Understand, but I'm not sure how we can help here further. We can have some best practices for writing the very first pull requests which enable `tmt` tests so that they include something like this:

    This pull request enables tests using tmt.

    Run tests directly on your localhost:
    sudo dnf install -y tmt
    tmt run --all provision --how local

    Run tests in a virtual machine:
    sudo dnf install -y tmt-provision-virtual
    tmt run

    See also a couple of virtualization tips here:
    https://tmt.readthedocs.io/en/latest/questions.html#virtualization-tips

    Check the Quick Start Guide to get more detailed introduction:
    https://docs.fedoraproject.org/en-US/ci/tmt/

Do you have any other suggestion how to make the first encounter with `tmt` even more intuitive?

**Comment by voxik** [comment]
~~~
$ tmt run
/var/tmp/tmt/run-030

/ci
Unsupported method 'virtual' in '/ci'.
~~~

This was my initial attempt. Let me comment it.

* `/var/tmp/tmt/run-030`
There is not much explanation, but well, it mentions `/var/tmp` so I might guess that this is some temporary directory. But if there was `Working directory: /var/tmp/tmt/run-030` it would give me more clue.

* `/ci`
This is first magical thing. Ok, there is `ci.fmf` in my directory, but why it mentions `/ci` instead? If ti said `ci.fmf` I would understand what is going on. If it mentioned, what it does with the file, that would be even better.

* `Unsupported method 'virtual' in '/ci'.`
If it said something like "'virtual' provisioner required to setup test environment for 'ci.fmf' is not available. Please choose different one using `provision -h <provisioner>`" that would be probably OKish. It does not need to go into installation business, because it it out of tmt scope on the first place. Being cmdline user, one can probably guess there is something like `--help` command or man page, which could provide more details. But in the current output, there is too much magic.

**Comment by psss** [comment]
Thanks much for providing detailed feedback. Yeah, some output might be confusing at the first sight. On the other hand we try to make it also concise which brings value for actual test execution. And that happens many many times comparing with the first encounter. I've updated the #406 pull request to also explicitly mention that the `/ci` is a plan. We can address other improvements in separate issues.
