### ISSUE TITLE
Support NO_COLOR to disable color output

### ISSUE THREAD

**Issue by psss** [psss/tmt#410]
What about supporting the `NO_COLOR` environment variable to disable output coloring. It could be useful for example for pipeline logs to make the a little bit more readable. There's already a bunch of apps and libs which use this [kind-of-standard](https://no-color.org/).

**Comment by psss** [comment]
Implementation should be easy: https://github.com/pallets/click/issues/1498

**Comment by thrix** [comment]
I am fine with that, but I like color output and we will definitely make use of it also later so it is displayed as it should be.
