### ISSUE TITLE
Command to list active forgotten virtual machines

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#416]
1minutetip has an option -r which gives you a list of your vm's that you started and did not kill.
tmt should have something similar in case you forget to finish a machine and it stays active somewhere.

**Comment by pvalena** [comment]
How about a whole new area, instead of one?
```
$ tmt list-runs --active
```

**Comment by psss** [comment]
Agreed, this could be definitely useful for other provision methods as well. It could also be something like

    tmt status --running
    tmt status --finished
    tmt status

The last one could provide an overview of available runs.

**Comment by FrNecas** [comment]
Great idea! I just checked how 1minutetip implements it and it queries for a specific machine name using openstack. Do you think this approach would be applicable to other provisions (I am not sure about testcloud and vagrant, it would definitely work with container and minute)? But perhaps it would be better to keep status somewhere in the run directory (it would be modified during the finish step) rather than relying on naming of machines.

**Comment by pvalena** [comment]
Yes, `vagrant` has global status.

But more generally- we could step into every folder and check whether the guest is running (as a backup way of status-polling f.e.). I'm incline not to rely on our status file, but that can be turned off by default (if there is a "state" file), and could be triggered by f.e. `--force-check`.

**Comment by pvalena** [comment]
@psss do you think having to check for every machine state in every workdir would be complicated / slow?

**Comment by psss** [comment]
I think checking all available test run workdirs (under the default location) should be ok and relatively simply/fast. We just check for runs where `provision` is done and `finish` is not done.

**Comment by FrNecas** [comment]
Sounds good to me and should be simple to implement (since we store the status of the step in `step.yaml`). I can try implementing this. What should the output be? Simply list out the paths (ids) to workdirs?

**Comment by psss** [comment]
What about listing one line per each run/plan combination? It could look like this:

```
disc prov prep exec repo fini
done done done done done done /var/tmp/tmt/run-225 /plans/basic
done done done todo todo todo /var/tmp/tmt/run-225 /plans/core
todo todo todo todo todo todo /var/tmp/tmt/run-225 /plans/helps
```

The `done` and `todo` labels could be nicely colored to quickly see what has been already completed.

**Comment by pvalena** [comment]
> What about listing one line per each run/plan combination? It could look like this:
> 
> ```
> disc prov prep exec repo fini
> done done done done done done /var/tmp/tmt/run-225 /plans/basic
> done done done todo todo todo /var/tmp/tmt/run-225 /plans/core
> todo todo todo todo todo todo /var/tmp/tmt/run-225 /plans/helps
> ```
> 

Wouldn't just the last '`done`' step suffice? This does not look much like user-friendly output to me.

**Comment by lukaszachy** [comment]
Or maybe print current running step if running and todo/done for not started/finished ? E.g.
```
done /var/tmp/tmt/run-225 /plans/basic
exec /var/tmp/tmt/run-225 /plans/core
todo /var/tmp/tmt/run-225 /plans/helps
```

**Comment by Athwale** [comment]
The reason for this was originally to be able to spot and kill machines that you left running, that sometimes happen if you get disconnected or you need more machines to run a test in background,....
Take a look at 1mt -r output:
1minutetip -r
[ INFO  ] Select instance which you want to reattach by providing its number
     1	user-1MT-RHEL-7.2-updates-123456-56789-2020-10-27-10-52 192.168.0.20
Which instance to attach? (number): 

if you then reattach you can kill it.
How would you use the output you are showing to kill the machine?
The ID could maybe be first and separated by spaces for easy copying by double click.

**Comment by psss** [comment]
>  How would you use the output you are showing to kill the machine?

In order to finish the reserved guest you would do the following:

    tmt run -i /var/tmp/tmt/run-225 finish

**Comment by Athwale** [comment]
Ok then.

**Comment by psss** [comment]
I like @lukaszachy's approach with a single value but still I see use cases when the long output would be useful as well. For example I fire up a bunch of integration jobs and want to know what's their status. Perhaps we could support `-l` and `--long` options to enable the detailed output?

**Comment by psss** [comment]
And, just brainstorming, we could also have `tmt status --finish` to finish all running jobs?

**Comment by pvalena** [comment]
> And, just brainstorming, we could also have `tmt status --finish` to finish all running jobs?

It's not obvious what it does IMHO, could we use instead something like `--run finish`?

**Comment by pvalena** [comment]
> I like @lukaszachy's approach with a single value but still I see use cases when the long output would be useful as well. For example I fire up a bunch of integration jobs and want to know what's their status. Perhaps we could support `-l` and `--long` options to enable the detailed output?

Or different short option? Not to confuse it with `-l` as `--last`.

**Comment by FrNecas** [comment]
> Or different short option? Not to confuse it with `-l` as `--last`.

What about simply verbose (so `-v` or `---verbose`)? I feel like that verbose exactly describes that it gives more information (in this case information about status of individual steps)

**Comment by psss** [comment]
> What about simply verbose (so `-v` or `---verbose`)?

Yeah, actually that's better and consistent with the rest.

**Comment by FrNecas** [comment]
Based on the discussion in this issue and our conversation on IRC, I propose the following solution:

The command `tmt status` will have 2 general options:
- `--verbose`/`-v` that adds information about step status to the output (see examples below)
- `path` that changes where the search begins. Defaults to `/var/tmp/tmt`. This can be useful as working directory of tmt can be set to anything so the users may want to provide a custom location. Example: Running `tmt status .` would list status from CWD.

Then there will be mutually exclusive filters (by default all disabled, so all runs and plans will be written out). For starters, we could start with the following filters:
- `--unfinished-guest` that lists out plans that have provision step `done` but the finish step is `todo`. In other words, there is a running VM somewhere that should be cleaned up. This is what @Athwale suggested in this issue. We could later add a way to finish the machines more easily (I am not really sure where such option would fit).
- `--active` lists out all plans where at least one step is `todo`.
- `--finished` the inverse of active, lists out all plans where all steps are `done`.

Now for some examples making use of what @psss and @lukaszachy suggested:

```
> tmt status
status id
done   /var/tmp/tmt/run-225  /plans/basic
exec   /var/tmp/tmt/run-225  /plans/core
todo   /var/tmp/tmt/run-225  /plans/helps
```

```
> tmt status --verbose
disc prov prep exec repo fini
done done done done done done  /var/tmp/tmt/run-225  /plans/basic
done done done todo todo todo  /var/tmp/tmt/run-225  /plans/core
todo todo todo todo todo todo  /var/tmp/tmt/run-225  /plans/helps
```

```
> tmt status --unfinished-guest
exec   /var/tmp/tmt/run-225  /plans/core
```

```
> tmt status --unfinished-guest --verbose
done done done todo todo todo  /var/tmp/tmt/run-225  /plans/core
```

```
> tmt status --active
exec   /var/tmp/tmt/run-225  /plans/core
todo   /var/tmp/tmt/run-225  /plans/helps
```

```
> tmt status --finished
done   /var/tmp/tmt/run-225  /plans/basic
```

The output could obviously be colored (use green for done, yellow for todo, keep the coloring consistent with the rest of tmt commands).

What do you think about this? Any feedback how to make it better? Any ideas for an option/command that would remove all unfinished guests?

**Comment by psss** [comment]
@FrNecas, thanks much for putting this together. Looks good to me in general. I've got a couple of comments/ideas:

Perhaps it would be good to make here the `run id` handling consistent with `tmt run` command. There it is possible to provide only directory name, for example like this:

    tmt run -i alpha
    tmt run -i errata-1234
    tmt run -i ksh-tier1
    tmt run -i ksh-tier2

So I would expect to be able to do:

    tmt status alpha
    tmt status errata
    tmt status ksh

In order to change the default root directory I'd propose to implement a new option. Perhaps `--root` or something similar:

    tmt status --root /my/custom/run/directory

For unfinished guests I'd suggest something shorter. What about one of these?

    tmt status --abandoned
    tmt status --deserted

For the simple output we could show full step name instead of four-letter abbreviations:

    > tmt status
    status  id
    execute /var/tmp/tmt/run-001
    prepare /var/tmp/tmt/run-002
    finish  /var/tmp/tmt/run-003
    done    /var/tmp/tmt/run-004

And one more thing: Shall we display individual plans always? Or only in verbose mode?

    > tmt status
    status  id
    done    /var/tmp/tmt/run-001
    execute /var/tmp/tmt/run-002
    prepare /var/tmp/tmt/run-003
    todo    /var/tmp/tmt/run-004

    > tmt status -v
    status id
    done   /var/tmp/tmt/run-001   /plans/core
    done   /var/tmp/tmt/run-001   /plans/basic
    done   /var/tmp/tmt/run-001   /plans/install
    exec   /var/tmp/tmt/run-002   /plans/core
    exec   /var/tmp/tmt/run-002   /plans/basic
    exec   /var/tmp/tmt/run-002   /plans/install
    todo   /var/tmp/tmt/run-003   /plans/core
    todo   /var/tmp/tmt/run-003   /plans/basic
    todo   /var/tmp/tmt/run-003   /plans/install

    > tmt status -vv
    disc prov prep exec repo fini
    done done done todo todo todo    /var/tmp/tmt/run-001   /plans/core
    todo todo todo todo todo todo    /var/tmp/tmt/run-001   /plans/basic
    todo todo todo todo todo todo    /var/tmp/tmt/run-001   /plans/install
    ...

Optionally, we could also introduce a dedicated options `--plan` to enable displaying individual plans.

**Comment by FrNecas** [comment]
@psss thanks for the feedback. I agree that listing status of one run directory should be possible.

I feel like adding `tmt status --root` could be confusing for the users. There is already a "global" option `tmt --root`, right? Adding 2 options of the same name under different commands can't be any good. Using the top-level root for status would be inconsistent with how it works in other subcommands.

I agree with using `--abandoned` instead of `--unfinished-guest` and with using the full step name in the non-verbose output. The 2 verbose levels also look good to me, in a lot of cases (for example when wanting to shut down unfinished provisions) a user will only care about the run id as they would run `tmt run --id /var/tmp/tmt/run-001 finish`.

**Comment by lukaszachy** [comment]
> And one more thing: Shall we display individual plans always?
IMHO proposed `-v` for plans and `-vv` for state table is nice.

**Comment by psss** [comment]
As discussed on the hacking session the clean up functionality (e.g. shutting down all/recent abandoned containers/machines) should be handled in a dedicated command outlined in #436.

**Comment by FrNecas** [comment]
Closing as `tmt status` has already been merged and the idea to automatically finish all plans with active provision has been proposed in #436
