### ISSUE TITLE
metadata.yaml does not contain all the information

### ISSUE THREAD

**Issue by sopos** [psss/tmt#419]
In case of requiring the _library(epel/epel)_ the resulting _matedata.yaml_ does not containg `require: library(epel/epel)` but it is replaced by the library's _require_. I'm not sure about the need to have the inherited requires from the library but definitely we need the original require.

**Comment by sopos** [comment]
custom (tmt non-specific) attributes are not propagated neither, e.g `mujklic: pokus`

**Comment by sopos** [comment]
@psss, this is kind of blocker for https://github.com/beakerlib/beakerlib/issues/57 as _rlImport_ won't be able to find the _library(X/Y)_ references.

**Comment by psss** [comment]
Yeah, understood. We've discussed this on the hacking session. I'll look into this soon.
