### ISSUE TITLE
Default timeout in provision/testcloud.py is too short for nested virtualization

### ISSUE THREAD

**Issue by kdudka** [psss/tmt#426]
The value of `DEFAULT_CONNECT_TIMEOUT` in `provision/testcloud.py` is too short for nested virtualization.  I run `tmt` in a virtual machine.  The nested virtual machine created by `tmt` is not ready to accept SSH connections in 10 seconds.  It takes approx 16 seconds on my Lenovo ThinkPad T480s laptop when there is no other load on the host.

Could you please either increase the value (I propose 60 seconds) or make it configurable?

**Comment by psss** [comment]
Makes sense. We could also improve the `DEFAULT_CONNECT_TIMEOUT` implementation not to check every second. Also make the usage consistent with `_get_url()` which actually sleeps 3 seconds between the attemps.

**Comment by pvalena** [comment]
> sted virtual machine created by `tmt` is not ready to accept SSH connections in 10 seconds. It takes approx 16 seconds on my Lenovo ThinkPad T480s laptop when there is no other load on the host.
> 
> Could you please either increase the value (I propose 60 seconds) or make it configurable?

@kdudka FYI: you can also switch to different "provisioning" method for the guest (like `container`, or `localhost`); alternatively, you can tell tmt to run the tests on any guest via ssh  (`connect`):
  https://tmt.readthedocs.io/en/latest/examples.html#provision-options

**Comment by kdudka** [comment]
@pvalena I see.  But one of the zsh/shell tests needs full virtualization:

https://src.fedoraproject.org/tests/shell/blob/84319ada/f/tests/login/main.fmf#_5

@psss Is there any way to encode the fact in test's metadata?

As it is now, one needs to manually analyze why the test failed with `provision --how container`.

**Comment by psss** [comment]
So far we do not have a dedicated attribute in the [tests specification](https://tmt.readthedocs.io/en/latest/spec/tests.html) for this. If you think this is something that would be useful / frequently used, let's file a new issue for that and discuss possible new attribute there.

**Comment by kdudka** [comment]
Proposed as #429.  Thanks!

**Comment by psss** [comment]
Should be fixed by #548.
