### ISSUE TITLE
`tests export --create --nitrate` removed 'require+' attribute, moved 'tier' down

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#427]
Repo root contains main.fmf with `require: py3c-devel`
Test contains main.fmf with attribute 
```yaml
require+:
- gcc
- python3-devel
- rpm-build
```
When I did `tmt tests export --nitrate --create` I saw: `Metadata successfully stored into ....`
But git diff shows more changes than expected:
```diff
-require+:
-- gcc
-- python3-devel
-- rpm-build
-tier: 1
 duration: 5m
+tier: 1
+extra-nitrate: TC#XXXXXX
```

I'd say that even moving `tier: 1` attribute is surprising, but at least it stays there.

**Comment by WOnder93** [comment]
For me it removed `adjust:` with all of its children (and also moved `tier:` down).

**Comment by psss** [comment]
This seems to be quite an unpleasant issue. I think we should fix this as soon as possible. @hegerj, will you have time to look into this in the coming days/weeks?

**Comment by hegerj** [comment]
Yes I will.

**Comment by jscotka** [comment]
There will be probably also a bigger issue with this updating yaml files.
I'm using virtual hierarchy structure inside FMF files like: 

```
components: [cockpit, cockpit-doc, cockpit-system, cockpit-bridge, cockpit-ws]
version_from_comps: [cockpit-bridge]

tags+: [Tier1]
relevancy: |
   distro != rhel-7: False
   distro = rhel-7 && arch=ppc64: False
beaker-task: /CoreOS/cockpit/Sanity/selenium-generic
test: selenium-base.py:BasicTestSuite
plans: [19006]
dependencies: []

/login:
   summary: "Check cockpit basic if is able to"
   /add_ssh_key:
      relevancy: |
         distro <= rhel-7: False
         distro = rhel-7 && arch=ppc64: False
      test+:  .test15BaseSSHKeyAdded
      summary+: "add ssh key for login user"
   /login:
      /sanity:
         test+: .test20Login
         summary+: "login with various scenarios: nonexisting user, bad password, proper user"
      /special_cases:
         test: selenium-login-special.py
         summary: "Check regressions in login cases, (text in bashrc, special login shell)"
         relevancy+: |
            distro <= rhel-8: False
```
tool `$ tmt test export --nitrate --create .` then generates tcms testcases:
```
Test case 'TC#0609282' created.
summary: Check cockpit basic if is able toadd ssh key for login user
components: cockpit
tags: fmf-export
default tester: jscotka@redhat.com
estimated time: 10m
automated: auto
status: CONFIRMED
arguments: SUBJECT=selenium-rhel8.4.py DEPENDENCIES=None PACKAGES='cockpit cockpit-doc cockpit-system cockpit-bridge cockpit-ws' VERSION_PACKAGES=cockpit-bridge
Structured Field: 
description: Check cockpit basic if is able toadd ssh key for login user
purpose-file: Cockpit testsuite
fmf id:
name: /Sanity/selenium-generic/login/add_ssh_key
url: https://git.src.osci.redhat.com:32101/tests//cockpit
Added warning about porting to case notes.
Test case 'TC#0609282' successfully exported to nitrate.
Metadata successfully stored into '/home/jscotka/git/cockpit-project/tests/cockpit/Sanity/selenium-generic/main.fmf'.
Test case 'TC#0609283' created.
summary: Check cockpit basic if is able tologin with various scenarios: nonexisting user, bad password, proper user
components: cockpit
tags: fmf-export
default tester: jscotka@redhat.com
estimated time: 10m
automated: auto
status: CONFIRMED
arguments: SUBJECT=selenium-rhel8.4.py DEPENDENCIES=None PACKAGES='cockpit cockpit-doc cockpit-system cockpit-bridge cockpit-ws' VERSION_PACKAGES=cockpit-bridge
Structured Field: 
description: Check cockpit basic if is able tologin with various scenarios: nonexisting user, bad password, proper user
purpose-file: Cockpit testsuite
fmf id:
name: /Sanity/selenium-generic/login/login/sanity
url: https://git.src.osci.redhat.com:32101/tests//cockpit
Added warning about porting to case notes.
Test case 'TC#0609283' successfully exported to nitrate.
Metadata successfully stored into '/home/jscotka/git/cockpit-project/tests/cockpit/Sanity/selenium-generic/main.fmf'.
Test case 'TC#0609284' created.
summary: Check regressions in login cases, (text in bashrc, special login shell)
components: cockpit
tags: fmf-export
default tester: jscotka@redhat.com
estimated time: 10m
automated: auto
status: CONFIRMED
arguments: SUBJECT=selenium-rhel8.4.py DEPENDENCIES=None PACKAGES='cockpit cockpit-doc cockpit-system cockpit-bridge cockpit-ws' VERSION_PACKAGES=cockpit-bridge
Structured Field: 
description: Check regressions in login cases, (text in bashrc, special login shell)
purpose-file: Cockpit testsuite
fmf id:
name: /Sanity/selenium-generic/login/login/special_cases
url: https://git.src.osci.redhat.com:32101/tests//cockpit
Added warning about porting to case notes.
Test case 'TC#0609284' successfully exported to nitrate.
Metadata successfully stored into '/home/jscotka/git/cockpit-project/tests/cockpit/Sanity/selenium-generic/main.fmf'.
```

after this comman `main.fmf` contains just:
```
test: selenium-base.py:BasicTestSuite
extra-nitrate: TC#0609284

```

So It totally breaks original files.

**Comment by jscotka** [comment]
BTW my feeling with yaml parsing and updating is, that after yaml file is stored it is converted to dict (maybe `OrderedDict` could help but not sure if possible improve yaml parser to use this in easy way) and then storing file stores stored it based on hash order in dict.

**Comment by jscotka** [comment]
It reminds me, that similar issue could be with yaml loader inside FMF, and my perspective on this issue is that most of work would be done on FMF side and TMT should be able to use FMF "saving" abilities then instead of own way.

FMF has data which node is stored in which files and probably for this case you want to update as latst file as possible. little trouble is that FMF does not remember raw data, just merged data +- and directory structure

- so probably it need to add to FMF some attributes, which exact part of dict inside file is used for this node (now there are just list of files)
- then just updating this node inside linked file, by new attribute (have to load this pure file again, to not dump merged `+` `-` items)
- then just dump the updated data to files if there are changes (maybe some attribute for changes?)

This way could be harder to implement (but not so much, just extending fmf node attributes and then just use it and dump), but cleaner for future usage and implementing more complicate updating/optimizing of fmf files.

**Comment by psss** [comment]
Yeah, I agree with @jscotka that the best long-term way forward here is to implement metadata update functionality directly in `fmf` which would then take care of all the complex hierarchy and elasticity issues. Let's track that feature in psss/fmf/issues/101 and for now resolve this issue by a simple workaround proposed in #515.
