### ISSUE TITLE
tmt export to nitrate does not handle the manual attribute

### ISSUE THREAD

**Issue by matusmarhefka** [psss/tmt#430]
Exporting test with the `manual` attribute set to `true` into nitrate creates an automated test case instead of the manual one.

**Comment by psss** [comment]
@hegerj, will you have a look at this?

**Comment by hegerj** [comment]
Will do, however it should be noted that creating manual cases in Nitrate through `tmt` is not supported.

**Comment by psss** [comment]
Resolved by #433.
