### ISSUE TITLE
crtl+c is caught by tmt in --interactive

### ISSUE THREAD

**Issue by sopos** [psss/tmt#431]
I would expect to be able to send such key strokes to the test itself. E.g. I use trap in the beakerlib tests and that callback is not run as `tmt` kills it completely.

**Comment by sopos** [comment]
maybe similar behaviour as `screen` or `tmux` could be used

**Comment by RHEmployee** [comment]
Hello. I can take a look at this issue.

**Comment by sopos** [comment]
It looks like it work for me now.
