### ISSUE TITLE
tmt test import should fix /usr/lib/beakerlib/beakerlib.sh path

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#432]
About 50% of tests use the older ". /usr/lib/beakerlib/beakerlib.sh" line which should replaced by newer ". /usr/share/beakerlib/beakerlib.sh" The test conversion process should fix that to make the tests compatible with newer environments.
The line may or may not end with || exit 1 in runtest.sh

**Comment by Athwale** [comment]
Some tests also contain /usr/share/rhts-library/rhtslib.sh instead of the lines above. I am not sure what this line is, it may also be a remnant of the old times.

**Comment by thrix** [comment]
I believe we do not need that anymore, but if you want to play safe, just add a check for existence of that file and source it just if it exists ....

**Comment by psss** [comment]
That line should also be converted into the new path. Those tests are only working because `beakerlib-redhat` still provides this old-backward-compatible symbolic link.

**Comment by hegerj** [comment]
I created PR #451 which replaces old beakerlib path with new one.
However I am not sure what to do with the `/usr/share/rhts-library/rhtslib.sh`. I've never seen it (and don't have it on my system, so I can't examine its importance - but I guess it's not needed any more). 
I am not quite sure what you mean by your comment @thrix . Do you suggest to add `test` for its existence in the imported test?

**Comment by Athwale** [comment]
The '/usr/share/rhts-library/rhtslib.sh' comes from beakerlib-redhat-1-33.fc29eng.noarch only about 300 of tests I have in my test folder ha it most tests have the other two paths.

**Comment by psss** [comment]
Yeah, the prehistoric rhts path should be also substituted with the fresh beakerlib one. In the above-mentioned backward-compatibility package it is just a symlink:

    /usr/share/rhts-library/rhtslib.sh -> /usr/share/beakerlib/beakerlib.sh

**Comment by hegerj** [comment]
Update of that path added to the pull request.
