### ISSUE TITLE
Manual test conversion should include scripts

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#434]
There are tests that are set as Manual but they do have a script in git. This is because the script needs user input or special manual actions to run properly. For example TC#315582
They can not be switched to Manual and Auto at the same time (which would make the Both), because such (Both) cases are scheduled as automated by wow --plan --fmf and these cases can not run in this way.
But when you convert using tmt test import --manual --plan XXX they get picked up as Manual but then the script is thrown away.

Using the TC mentioned above as example:

Converting with --manual:
test.md is empty
This can not be executed by a tester if you get this test in your errata plan once tmt will start taking care of that.

Normal conversion:
Because the test has a script in git, it has a folder in test git and thus will get converted as normal test by an unsuspecting user or automated script.
By converting it with tmt test convert/import you get a testcase which would be wrongly scheduled as automated.
The conversion command should skip such cases with some kind of a warning output.

For more examples, check the blocking issues jira.

**Comment by hegerj** [comment]
Test cases such as this should be imported with the rest of the automated test cases but should be marked as Manual.
This is a bug, thanks for catching that.

**Comment by Athwale** [comment]
I am not sure now, but when automatically converting manual cases by running import --manual --plan XXX these semi automated cases will be picked up and end up duplicated in two places once in the regular for example Regression folder marked as manual and once in the Manual folder as a regular manual test pulled from tcms.

**Comment by psss** [comment]
As for now I would just suggest to remove the duplicate from the Manual test folder. We can look into making this even more comfortable for the user in the future. But currently I'd say we have other more pressing issues.

Or, one more thought: If these cases are marked as both `automated` and `manual` we could detect that and take a special action. Or... what about skipping test cases which have the `script` field non empty during `tmt import --manual`?

**Comment by thrix** [comment]
This is marked as a blocker for the team to move forward with migration, could we prioritize this somehow @hegerj ?

**Comment by hegerj** [comment]
It's a next thing on my list.

**Comment by thrix** [comment]
@hegerj thanks man!

**Comment by psss** [comment]
Support for skipping manual tests with script has been merged in #474. Is there anything else which should be covered here?

**Comment by hegerj** [comment]
I believe last thing to be covered is now in PR #488 .

**Comment by psss** [comment]
Thanks, #488 has been merged.
