### ISSUE TITLE
tmt login requires `rsync`

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#437]
Execution of `tmt run  provision --how connect --guest FQDN login` failed.
'rsync' is used to upload workdir to the remote machine. 

IMHO tmt shouldn't assume that some packages are always present but install them to the guest if necessary.

```
        login: Starting interactive shell
            Push workdir to guest 'FQDN'.
            Run command 'rsync -Rrz --links --safe-links --delete -e "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null" --safe-links /var/tmp/tmt/run-105/plans/default root@FQDN:/'.
            err: Warning: Permanently added 'FQDN,A.B.C.D' (ECDSA) to the list of known hosts.
            err: bash: rsync: command not found
            err: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
            err: rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
            Command returned '12'.

stderr (4/4 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Warning: Permanently added 'FQDN,A.B.C.D' (ECDSA) to the list of known hosts.
bash: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]

Failed to run command 'rsync -Rrz --links --safe-links --delete -e "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null" --safe-links /var/tmp/tmt/run-105/plans/default root@FQDN:/'.

```

**Comment by lukaszachy** [comment]
Looks it has to be present on REMOTE as well.

**Comment by psss** [comment]
This should be fixed by #553 but it's still necessary to have the `prepare` step enabled:

    tmt run provision --how connect --guest my.test.box prepare login

Is this sufficient? Any ideas how to improve this even more?

**Comment by lukaszachy** [comment]
Do we need to call rsync for login? Help for `tmt run login` says ```Provide user with an interactive shell on the guest.```

**Comment by psss** [comment]
So the way how it works is that we provide the interactive shell in the (synced) workdir so that one can experiment with the test code and do similar stuff. Perhaps we could apply a workaround for this specific case and use an arbitrary remote directory?

**Comment by lukaszachy** [comment]
Or maybe just update the documentation so user is not surprised with sync

**Comment by psss** [comment]
I've updated #553 to only give a warning when `guest.push()` failes during the `login` plugin execution. This should cover this use case as well. Please, verify. Thanks.

**Comment by lukaszachy** [comment]
Works as I expected. Thank you.
