### ISSUE TITLE
[RFE] report --how html 

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#441]
Use case: tmt run for a lot of cases for later review.

It is easier to see fail/pass in browser and click for logs then to process text from terminal
Inspiration: restraint -> creates index.html with summary + links to logs

```tmt run report --how html --open``` could open the index page in default browser
Otherwise just a location of index will be printed.

The index.html (+css/js) could be placed to the workdir of 'report' step - No need to copy any of files as they are already there.

**Comment by psss** [comment]
Very nice! I like this and agree with the proposed syntax.

**Comment by lukaszachy** [comment]
I started working on this.
