### ISSUE TITLE
Create test metadata from bugzilla bug like beaker-wizard

### ISSUE THREAD

**Issue by pemensik** [psss/tmt#444]
``beaker-wizard -b <bugid>`` can create new test for beakerlib. It would be nice if tmt had alternative.

It fetches few descriptions from bugzilla and prepares skeleton for a new test. Its main feature its preparing test name and linking bug to it. Because beaker-wizard is not yet updated, I expect it to be deprecated. Is there already any plan to offer similar functionality?

**Comment by lukaszachy** [comment]
A bit related #215 to add attribute for linking the bug.

Command `tmt tests create --bugzilla <bugid>` will be nice indeed.

**Comment by psss** [comment]
Possibly a duplicate of #368?

**Comment by pemensik** [comment]
Okay, duplicate of #368
