### ISSUE TITLE
fmf-id `path` attribute ignored for libraries

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#446]
I want to test that wow command correctly parses library references, so I want to store fmf tree in `tests/fmf` subdirectory.
However when I tried to reference "library" as bellow I run into `Repository 'GIT_REPO' does not contain fmf metadata.` which is kind of true since fmf metadata are deeper as mentioned in the  `path` attribute.

Documentation says `a full fmf identifier` is supported and path is part of that
```
/first:
  test: ./runtest.sh
/second:
  test: ./runtest.sh
  require:
    - url: GIT_REPO
      name: /first
      path: /tests/fmf

**Comment by sopos** [comment]
Beakerlib will soon support libraries in any path, see https://github.com/beakerlib/beakerlib/pull/78/commits/bd5ce4027aea2c941c3da34780f668671a39be47 if the related PR is merged.
Not sure if this will solve what you are trying to achieve but it is at least related.
