### ISSUE TITLE
Standardize bug tracker references in test metadata

### ISSUE THREAD

**Issue by WOnder93** [psss/tmt#461]
It would be nice to have some standard and machine-readable way to add references to bug trackers in tests. I think the only semantic link that makes sense here is "this test covers these bugs", so probably a simple list of bug references would be enough. Also, bug trackers can be distinguished based on the URL, so a simple list of URLs would likely suffice:
```
links:
- https://bugzilla.redhat.com/show_bug.cgi?id=123
- https://github.com/my/project/issues/123
```
Side note: This could be used in `tmt export --nitrate` to populate the list of associated RHBZs.

**Comment by psss** [comment]
We have an ongoing (well actually it's a bit sleeping now) discussion about this in #215.

**Comment by WOnder93** [comment]
Ah, missed that, sorry... Feel free to close this one as a duplicate.

**Comment by psss** [comment]
Ok, let's continue the discussion in #215.
