### ISSUE TITLE
tmt init --template base walks through irrelevant parent directories of a directory where it was invoked

### ISSUE THREAD

**Issue by fernflower** [psss/tmt#465]
fmf==0.13.1
tmt installed from master, ca4e6de8c82dc23ac744ad3cc7a0930d16b43898
On a fresh install I noticed that `tmt init --template base` launched in a deeply nested folder was running ages.
Some debugging and prints later:
```
(.venv) [ivasilev@localhost tmp]$ mkdir -p a/really/deep/directory/structure/project
(.venv) [ivasilev@localhost tmp]$ cd /tmp/a/really/deep/directory/structure/project/
(.venv) [ivasilev@localhost structure]$ tmt init --template base
(.venv) [ivasilev@localhost project]$ tmt init --template base
Path to create a tree is /tmp/a/really/deep/directory/structure/project

Root to be walked next is /tmp/a/really/deep/directory/structure

Root to be walked next is /tmp/a/really/deep/directory

Root to be walked next is /tmp/a/really/deep

Root to be walked next is /tmp/a/really

Root to be walked next is /tmp/a

Root to be walked next is /tmp

Root to be walked next is /

Path to create a tree is /tmp/a/really/deep/directory/structure/project

Tree '/tmp/a/really/deep/directory/structure/project' initialized.
Applying template 'base'.
Directory '/tmp/a/really/deep/directory/structure/project/tests/example' created.
Test metadata '/tmp/a/really/deep/directory/structure/project/tests/example/main.fmf' created.
Test script '/tmp/a/really/deep/directory/structure/project/tests/example/test.sh' created.
Directory '/tmp/a/really/deep/directory/structure/project/plans' created.
Plan '/tmp/a/really/deep/directory/structure/project/plans/example.fmf' created.
```

Prints were installed at https://github.com/psss/tmt/blob/master/tmt/base.py#L733 and https://github.com/psss/fmf/blob/master/fmf/base.py#L109
My suspect is that https://github.com/psss/fmf/blob/master/fmf/base.py#L104 is the culprit, why should it walk files outside requested directory?

**Comment by fernflower** [comment]
The behavior is also inconsistent for `tmt test ls` if invoked inside a leaf project directory vs inside a non-leaf project directory where no tests can be found. In the first case it searches just the project directory; in the second case all parent directories are walked one-by-one before giving up.
```
(.venv) [ivasilev@localhost project]$ pwd
/tmp/a/really/deep/directory/structure/project
(.venv) [ivasilev@localhost project]$ ls
(.venv) [ivasilev@localhost project]$ tmt test ls
Path to create a tree is .

(.venv) [ivasilev@localhost project]$ cd ..
(.venv) [ivasilev@localhost structure]$ pwd
/tmp/a/really/deep/directory/structure
(.venv) [ivasilev@localhost structure]$ ls
project
(.venv) [ivasilev@localhost structure]$ tmt test ls
Path to create a tree is .

Root to be walked next is /tmp/a/really/deep/directory

Root to be walked next is /tmp/a/really/deep

Root to be walked next is /tmp/a/really

Root to be walked next is /tmp/a

Root to be walked next is /tmp

Root to be walked next is /

No metadata found in the '.' directory. Use 'tmt init' to get started.
```

**Comment by psss** [comment]
It is expected that `fmf` tries to find the root of the metadata tree marked by the `.fmf` folder by walking through all parent directories up to the filesystem root. See also documentation for metadata [trees](https://fmf.readthedocs.io/en/stable/concept.html#trees).

This, however, should definitely not take ages as it only checks for the presence of the special `.fmf` folder. Do you have any idea why it took so long? Can you still reproduce?

**Comment by fernflower** [comment]
Mystery solved - for some strange reason I had an .fmf directiry in the user home directory, and when I was running `tmt init` it was blocked on growing the home directory tree at https://github.com/psss/fmf/blob/master/fmf/base.py#L86

Thank you, I will close the issue now.
