### ISSUE TITLE
tag can be set to None, with weird consequences

### ISSUE THREAD

**Issue by t184256** [psss/tmt#469]
I've accidentally removed the last tag of the test without removing the `tag:` and got bit in a non-obvious way later. Reproducer:

```
$ mkdir tmt-nulltag; cd tmt-nulltag; tmt init
$ tmt test create --template shell nulltag-test; echo 'tag: ' >> nulltag-test/main.fmf
$ tmt tests ls
/nulltag-test
$ tmt tests ls --condition '"nonex" not in tag'
Traceback (most recent call last):
--- 8< ---
 File "/usr/lib/python3.7/site-packages/fmf/base.py", line 379, in prune
    for condition in conditions]):
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 379, in <listcomp>
    for condition in conditions]):
  File "/usr/lib/python3.7/site-packages/fmf/utils.py", line 168, in evaluate
    return eval(expression)
  File "<string>", line 1, in <module>
TypeError: argument of type 'NoneType' is not iterable
$ tmt tests ls --condition 'tag is None'
/nulltag-test
```

Expected result: either
a. setting `tag` to `None` is not allowed at all, all consequent operations crash
b. setting `tag` to `None` autocasts it to an empty list

**Comment by martinky82** [comment]
I would go along the b. way: if tags: is empty, then treat it as an empty list

**Comment by lukaszachy** [comment]
Agree. This looks that condition is running with initial fmf metadata, without applying tmt defaults and conversions.

**Comment by martinky82** [comment]
Wouldn't it be best to fix this issue in fmf? I tried adding except TypeError here:

https://github.com/psss/fmf/blob/master/fmf/base.py#L473

(just logging the problem, no real action taken) and it works as expected.

**Comment by lukaszachy** [comment]
Likely in both. 
However FMF itself doesn't know about 'defaults' or automatic type conversion so special --filter and --condition should run on TMT processed Tree.

**Comment by lukaszachy** [comment]
IMHO Traceback is something user shouldn't ever see unless they really try to cause it.

**Comment by martinky82** [comment]
> IMHO Traceback is something user shouldn't ever see unless they really try to cause it.

Agreed
