### ISSUE TITLE
Implement a new tail subcommand

### ISSUE THREAD

**Issue by psss** [psss/tmt#482]
Now when we have the debug log in a single file it's quite easy to watch what's happenning under the hood when tests are executed with low verbosity:

    # the first terminal
    tmt run -v

    # the second terminal
    tail -f /var/tmp/tmt/run-123/log.txt

It would be nice, however, to have a dedicated command which would support this functionality. Perhaps something like this?

    tmt run --last --tail
    tmt run --id run-123 --tail

Does it make sense to you? Would it be worth implementing this?

**Comment by pvalena** [comment]
@psss Is it supposed to run instead of regular output? What's the difference from some verbose output f.e.?

In case of `--last` it makes sense, as I myself running ```tmt run -l -vvv report -f ``` quite often.

**Comment by lukaszachy** [comment]
Hm, I find it confusing if it is in `run --tail`:
`tail` usually prints end of the output, for following updates you want `tail -f` as you mention in the example. So it will be similar but not same'. If it was called 'follow'? as `tmt run --follow`?

**Comment by psss** [comment]
> What's the difference from some verbose output f.e.?

The use case is when you run tests with low verbosity but then suddenly you realize tests are being executed too slowly so you want to look under the hood to see what's actually happenning there. Thus you open a second terminal and...

> If it was called 'follow'? as tmt run --follow

Sounds good to me.

**Comment by thrix** [comment]
yeah `follow` is is better, and it would be very handy

**Comment by pvalena** [comment]
> > What's the difference from some verbose output f.e.?
> 
> The use case is when you run tests with low verbosity but then suddenly you realize tests are being executed too slowly so you want to look under the hood to see what's actually happenning there. Thus you open a second terminal and...
> 

Ah, now it makes sense! So it's actually a run, you need `--last` or `--id` for it then. I also agree on `--follow`.

Wouldn't this syntax make more sense then?
```
$ tmt run follow --id ...
$ tmt run follow --last
```

**Comment by psss** [comment]
The `--id` and `--last` are already defined options under the `run` subcommand. I don't see benefit in redefining them again under a dedicated subcommand. But the basic question is: Do we expect any other options to be needed for the new `follow` feature? If not, I think a single option under the `run` subcommand would be just enough.

    tmt run --last --follow
