### ISSUE TITLE
`tmt export --nitrate [--create]` for manual tests

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#487]
Also manual tests should be exportable to nitrate (and be able to be created from scratch).
Export should try to render `test.md` into nitrate document as html (reverse of tmt.convert.read_manual_data) however it will be a best effort (import -> export -> import is not guaranteed to provide identical test.md nor case document)

**Comment by dkarpele** [comment]
I will have a look

**Comment by lukaszachy** [comment]
And ServerProxy to Nitrate is a private attribute of almost every object, e.g. `nitrate.User()._server` 
So quick way to update could be to call `nitrate.User()._server.TestCase.store_text(609679, 'is ACTION', 'Effect', 'Setup', '<ul>  <li>Coffee</li>  <li>Tea</li>  <li>Milk</li></ul>')`

**Comment by psss** [comment]
Fixed in #641.
