### ISSUE TITLE
import from Nitrate creates sometimes contacts `None <email@domain.com>`

### ISSUE THREAD

**Issue by Jakuje** [psss/tmt#503]
The import of a test (`tmt test import`) firstly creates valid contacts from Makefile (even though probably outdated), but then creates "None" contacts if the user does not have a name in TCMS.

Log excerpt:
```
Makefile found in '/home/jjelen/tests/.../Makefile'.
task: /CoreOS/...
summary: Test for BZ#123123 (RSA-{E,S} public keys cannot be imported)
test: ./runtest.sh
contact: Name Name <name@redhat.com>          <<<<<
component: gnupg2
duration: 15m
require: library(distribution/Cleanup) library(distribution/testUser)
recommend: gnupg2
Purpose found in '/home/jjelen/tests/.../PURPOSE'.
description:
Bug summary: RSA-{E,S} public keys cannot be imported
Nitrate test case found 'TC#123123'.
extra-summary: /CoreOS/...
contact: None <name@redhat.com>             <<<<<< 
```

I think the import from nitrate should be clever enough to notice `None` values and not produce these bogus contacts. The simplest solution would be to exclude the name. Something along the lines as (untested)
```
diff --git a/tmt/convert.py b/tmt/convert.py
index 3991c06..7d7574a 100644
--- a/tmt/convert.py
+++ b/tmt/convert.py
@@ -489,8 +489,11 @@ def read_nitrate_case(testcase):
         echo(style('extra-summary: ', fg='green') + data['extra-summary'])
     # Contact
     if testcase.tester:
-        data['contact'] = '{} <{}>'.format(
-            testcase.tester.name, testcase.tester.email)
+        if testcase.tester.name:
+          data['contact'] = '{} <{}>'.format(
+              testcase.tester.name, testcase.tester.email)
+        else:
+          data['contact'] = '<{}>'.format(testcase.tester.email)
         echo(style('contact: ', fg='green') + data['contact'])
     # Environment
     if testcase.arguments:
```
The better possibility would be to pull the names from other source if they are not available from TCMS.

**Comment by psss** [comment]
Plus, perhaps, if the email address in the `Makefile` is the same as in `Nitrate` use the name from there instead of `None` or email only.

**Comment by Jakuje** [comment]
This is a good idea too. I fixed the issues that bothered me manually using sed (these were just two names), but this issue might live in other repositories and might be worth also fixing in existing metadata too.

**Comment by psss** [comment]
@adka1408 is working on this.
