### ISSUE TITLE
Do not use 'master' as a default ref

### ISSUE THREAD

**Issue by sopos** [psss/tmt#505]
When _ref_ in the _fmf id_ is not defined the `master` is used by default.

As the _problematic language_ topic is spreading world wide like covid, also github has changed the default branch to `main`.

It would be much better if the default was the original git's default branch. If you `git clone` a repo it will automatically checkout the default branch. Git has also a command for setting it `git remote set-head origin --auto`. This is definitely the direction we should go.

**Comment by psss** [comment]
This proposal relates to the following two specifications:

* [fmf identifier](https://fmf.readthedocs.io/en/latest/concept.html#identifiers)
* [fmf discover plugin](https://tmt.readthedocs.io/en/latest/spec/steps.html#fmf)

If we decide to change the default we should ensure these two are kept consistent.

**Comment by lukaszachy** [comment]
Fedora has already changed - https://fedoraproject.org/wiki/Changes/GitRepos-master-to-main 
So current default (tmt) doesn't work anymore

**Comment by psss** [comment]
Looks like an important issues which should be addressed soon. Proposing for 1.3.
