### ISSUE TITLE
tmt test convert/import should include bugs form tcms using the new link attribute

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#527]
Makefiles used to contain a list of bugs for which the test was written, these bugs were then stored in tcms with the case and new bugs were added in tcms in case the same case was usable for more bugs.

With current converted main.fmf from Makefile unless the name of the test contains the bug number it is not possible to tell which bugs the test tests. It is often useful to be able to look at the bugs for the test and original reproducers when you are for example fixing a broken test or looking for related bugs on other os versions or figuring out whether the test is supposed to fail due to an unfixed bug.  

The link attribute https://github.com/psss/tmt/pull/215 seems to be designed for that.

tmt test convert should import this data from tcms and store it in the test's main.fmf

**Comment by Athwale** [comment]
What is the status here? I see something closed here, does it work already?

**Comment by hegerj** [comment]
The closed issue is a duplicate. No progress on this issue so far as far as I know.

**Comment by psss** [comment]
I will look into this.
