### ISSUE TITLE
tmt tests lint reports a need for path

### ISSUE THREAD

**Issue by sopos** [psss/tmt#529]
`tmt tests lint` reports `pass directory path must be defined`, however the path is auto-constructed in most cases. Such check basically does not make sense as there's apparently no way to make this to fail.

**Comment by psss** [comment]
It's true that the default `path` is used when not explicitly defined. So the only weird cases are probably these:

    path: ''
    path: ' '

Currently `tmt test lint` does not cover them. Although they look like corner cases, I'd still cover them with a check for at least one non-white-space character. @lukaszachy, what do you think?

**Comment by sopos** [comment]
shouldn't is start with _/_ if defined?

**Comment by psss** [comment]
Right you are, the [spec](https://tmt.readthedocs.io/en/latest/spec/tests.html#path) says:

    Use a string containing an absolute path starting with slash.

So we should check for the slash as well.

**Comment by sopos** [comment]
then I think there should be two checks
1. it starts with `/`
2. the path exists

**Comment by psss** [comment]
Agreed, makes sense.
