### ISSUE TITLE
export nitrate: Change case summary to {repo}{name} - {summary}

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#531]
See this test https://src.fedoraproject.org/rpms/autoconf/blob/rawhide/f/tests/runstatedir/main.fmf

Currently `tmt export --nitrate --create` will create new Nitrate case with summary `The test for runstatedir feature`

However in in test results review were many components and tests are mixed we use summary to know component and exact test on first glance without opening the test case.

Proposal:
Create summary in the form of `<basename of repo><name> - <summary>` unless  `extra-summary` attribute is present (this part stays the same as now

So such test cases will get summary of `autoconf/tests/runstatedir - The test for runstatedir feature` which is imho a good compromise

**Comment by hegerj** [comment]
I am bit worried that there will be tests with quite long names (tests with longer summaries) but hopefully it will be manageable.
Increased readability is probably worth it and you can always override it with your own `extra-summary`.

**Comment by lukaszachy** [comment]
> I am bit worried that there will be tests with quite long names (tests with longer summaries) but hopefully it will be manageable.
> Increased readability is probably worth it and you can always override it with your own `extra-summary`.

Ah, very good point. https://github.com/Nitrate/Nitrate/blob/release-3.8.17/tcms/testcases/models.py#L124 says that max lenght is 255.
