### ISSUE TITLE
Support '.' as current dir for NAME in `tmt tests create`

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#534]
Use case: As a test author I want to create new test in the current directory using specified template

Currently happens:
1. mkdir -p some/nice/dir/structure
2. cd  some/nice/dir/structure
3. tmt tests create -t beakerlib .

Test script '$HOME/<repo>/./test.sh'  created.

**Comment by psss** [comment]
Nice little improvement. Should be easy to implement using relative path from the root.

> Test script '$HOME//./test.sh' created.

Actually it creates the new test in the metadata tree root directory.
