### ISSUE TITLE
tmt import from Nitrate doesn't import Notes, Setup, Actions, etc.

### ISSUE THREAD

**Issue by tomato42** [psss/tmt#536]
when running `tmt import` on a Nitrate test script, the additional metadata from Notes, Setup, Actions, Breakdown, and Expected Results is not imported.

Those fields include important metadata about the test case. For example, the Notes filed commonly includes information why particular architecture or version is excluded from testing.

**Comment by psss** [comment]
Storing setup and friends should be working.

```
> tmt test import
...
Test case successfully stored into '/home/psss/git/tmt/examples/convert/test.md'.
Metadata successfully stored into '/home/psss/git/tmt/examples/convert/main.fmf'.

> cat test.md 
# Setup
Do this and that to setup the environment.

# Test

## Step
Step one.

Step two.

Step three.

## Expect
Expect one.

Expect two

Expect three.

# Cleanup
This is a breakdown.
```
And the `StructuredField` header and footer are imported into description.  Are you using the latest `tmt`?

**Comment by tomato42** [comment]
Yes, I can confirm it works as expected with 1.6.0, must have used old version.
