### ISSUE TITLE
Unsupported provision method, but no provisioning required

### ISSUE THREAD

**Issue by ep69** [psss/tmt#539]
I am running something like: `tmt run plans -n interop discover -v` and I get an error: `Unsupported provision method 'virtual' in the '/plans/interop' plan.`

My expectation was that it wouldn't try to provision anything, just discover tests. Perhaps config parser is trying to be clever soon (and fails)?

**Comment by psss** [comment]
This is caused by the fact that at the beginning the whole plan configuration is always checked and all steps are assigned their appropriate plugin implementation using `Plugin.delegate`. Perhaps, for steps which are not enabled we could only give a warning.
