### ISSUE TITLE
Use "session" as a default in the testcloud provision plugin

### ISSUE THREAD

**Issue by psss** [psss/tmt#541]
In [BZ#1914194](https://bugzilla.redhat.com/show_bug.cgi?id=1914194) @martinpitt suggests to use `session` instead of `system` as a default for the `testcloud` plugin. I'm not an expert on `libvirt` and friends. @thrix, @pvalena, @FrNecas, what do you think? Does it make sense? Could it break anything?

**Comment by thrix** [comment]
if we make it working with `session`, I do not see a reason why not to use it. Also I plan to start Fedora Silverblue, so finding a working tmt with toolbox would be nice :) Would be also good to check with `testcloud` maintainers, if they have some insight, I remember we had some discussion in the beginning for using `session`, but I do not remember the details anymore.

CC @frantisekz

**Comment by pvalena** [comment]
Yes, `qemu://session` is better :) I've mentioned it before, but I'm not sure `testcloud` knows how to do that. Note that due to it running in userspace, you can't create/manage local networks for the VM etc.

**Comment by martinpitt** [comment]
@pvalena: Right, this is where my half-hearted attempt in https://bugzilla.redhat.com/show_bug.cgi?id=1914194#c2 stopped, as I didn't want to sink too much time into this before getting some agreement that this is also what you want.

In [cockpit bots](https://github.com/cockpit-project/bots/blob/master/machine/machine_core/machine_virtual.py#L134) we use a [QEMU socket network](https://wiki.qemu.org/Documentation/Networking#Socket) for unprivileged instances. With that, multiple VMs can talk to each other in a private network, and you can also [forward ports](https://github.com/cockpit-project/bots/blob/master/machine/machine_core/machine_virtual.py#L157) (usually ssh) to the host.

This may be a little less performant than a real bridge, but for some ssh commands and scp it's really good enough. This has the advantage that it does not need any setup nor privileges on the host -- no bridges, no persistent resources, no persistent config, everything works in toolbox and in containers, and thus it is very safe to run.

**Comment by psss** [comment]
> This has the advantage that it does not need any setup nor privileges on the host -- no bridges, no persistent resources, no persistent config, everything works in toolbox and in containers, and thus it is very safe to run.

Sounds like a better approach to me. Especially if it means that we can run this under containers.

**Comment by frantisekz** [comment]
> Yes, `qemu://session` is better :) I've mentioned it before, but I'm not sure `testcloud` knows how to do that. Note that due to it running in userspace, you can't create/manage local networks for the VM etc.

Testcloud should be able to handle qemu://session (eg. testcloud instance -c qemu:///session create test -u fedora:33 ), but it seems broken. I'll take a look into it, but it might be early next week as I am running low on free cycles right now.

Some discussion about this was in testcloud repo: https://pagure.io/testcloud/issue/64

**Comment by frantisekz** [comment]
Okay, I've found time to dig into it a bit.

I've ended up with https://pagure.io/testcloud/pull-request/83# , I'll create a copr repo with that applied in the afternoon, so you can try if that works for you.

Or if you can apply the changes into your pipeline and want to try, you basically need just to set connection in all the testcloud classes and functions you're using from default 'qemu:///system' to 'qemu:///session' .

**Comment by frantisekz** [comment]
Okay, the testing copr is here: https://copr.fedorainfracloud.org/coprs/frantisekz/testcloud-wip/

@psss

**Comment by psss** [comment]
@frantisekz, thanks for preparing the testing copr. I tried the fresh package and everything worked fine. However, not sure how to confirm / verify that `qemu:///session` was actually used. Any hint? @martinpitt, could you try if it works for your use case?

**Comment by frantisekz** [comment]
> @frantisekz, thanks for preparing the testing copr. I tried the fresh package and everything worked fine. However, not sure how to confirm / verify that `qemu:///session` was actually used. Any hint? @martinpitt, could you try if it works for your use case?

I am not sure if you can run commands on the guest, but 'virsh -c qemu:///session list'  should give you all the vms running in the session mode.

I can try to take a look at adding more logging testcloud side, but passing the connection argument to testcloud should be pretty reliable way to make it run through a different connection.

**Comment by martinpitt** [comment]
Thanks for looking into this! I sent a first review to https://pagure.io/testcloud/pull-request/83#

**Comment by frantisekz** [comment]
> Thanks for looking into this! I sent a first review to https://pagure.io/testcloud/pull-request/83#

Thanks for the review, I've updated the PR last week, just pinging here in case you aren't getting notifications from pagure. copr repo was updated too.

**Comment by psss** [comment]
Will be fixed by #642 but we need to wait until the fresh `testcloud` is released.
