### ISSUE TITLE
tmt asks for password when rhel x (where x is bigger than seven plus 1). It should be same for fedora rawhide.

### ISSUE THREAD

**Issue by RHEmployee** [psss/tmt#559]
There is issue when I want to shedule $(subject), then unsupported ssh key is used for ssh connection.

How:
tmt run -vvvddd provision -h minute -i rhel-x login finish

Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /usr/share/GAGA-tools/1minutetip/1minutetip root@10.0.x.x cat /etc/os-release'.
            err: Warning: Permanently added '10.0.x.x' (ECDSA) to the list of known hosts.
root@10.0.x.x's password:

This is already solved in 1minutetip images and code base.

**Comment by FrNecas** [comment]
Closing since the plugin has been moved downstream and this seems to be related to networks
