### ISSUE TITLE
Documentation `Description` is not clear enough

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#571]
The first few paragraphs in `Description` are very important, but this is not clear enough:

```
The tool provides a user-friendly way to create, debug and easily run tests from your laptop across different environments. It also allows to easily convert old metadata, list and filter available tests and verify them against the L1 specification.
```
It should explicitly state that `L2 metadata` **are** `Plans / specification`.

**Comment by pvalena** [comment]
Likewise: 

```
Plans are used to group tests and configure individual test steps defined by the L2 specification. They describe how to select tests for execution, how to provision the environment, how to prepare it for testing or how the test results should be reported.
```

**Comment by pvalena** [comment]
@jackorp Please follow up.

**Comment by psss** [comment]
@pvalena, do you propose something like this?

    Plans, which imlement the L2 specification, are used to group tests and configure...

What is not clear enough in the paragraph describing tests?

**Comment by jackorp** [comment]
I would appreciate a change that would look like the proposed
```
Plans, which implement the L2 specification,...
```
and likewise for L1.

Moreover, the paragraph mentioning L1 metadata does not make it clear to me what is it for. I read that (in short), ok, the tool can do stuff with tests from my laptop in different environments and I can convert old metadata and verify them. However, for me, it is very different from the content of description paragraphs mentioning L2 and L3.

The main difference I see is that the L1 paragraph does not mention what you can see in the other two e.g. what does the L1 can store or can do.

**Comment by psss** [comment]
This should be covered by #643. Feel free to reopen if anything important is still missing.
