### ISSUE TITLE
discover.fmf modified-only doesn't work for virtual tests

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#573]
Firstly: This discover option is great and I'd love to use it.
However - I have many virtual cases, e.g. instead of `/smoke` I have `/smoke/py38` and so on.

I propose to remove (or make optional) final `$` from regexp constructed by modified directories.
That way it can work for virtual cases as well. 
Also - If you have modified file in the parent directory you are most likely to modify .fmf file which affects metadata in all children nodes.

**Comment by psss** [comment]
Sounds good to me. @WOnder93, what do you think about the proposed change?

**Comment by WOnder93** [comment]
I though about it a bit and it seems reasonable. The only downside I could think of is that it could run too many tests if you change something high in the hierarchy (e.g. if you modify the toplevel `.gitignore` file, it will run all tests). But I can't think of a good way to avoid it (maybe some upper limit on selected tests specified in the plan?) and the pros probably outweigh the cons, so I'm in favor of the change.

**Comment by psss** [comment]
Resolved by #664.
