### ISSUE TITLE
simple prepare phase took for me from 1-3 minutes

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#58]
most of the time it was autodetecting stuff.

```
[mvadkert@freedom /var/tmp/tmt/run-051/plans/basic/provision/gchBHnRSKzzDtZxm]$ time vagrant --debug provision --provision-with prepare
real	1m47.346s
```

It would be awesome if we could say to vargrant this is a RHEL or Fedora machine, so he does not need to do the autodetection by himself.

_Originally posted by @thrix in https://github.com/psss/tmt/pull/47_

**Comment by lukaszachy** [comment]
Vagrant plugin has been removed. Closing this issue
