### ISSUE TITLE
 Outline syntax for container provision

### ISSUE THREAD

**Issue by psss** [psss/tmt#6]
@hroncok suggested in #4 the following syntax for executing tests in a container:

    tmt --docker fedora:rawhide --cap-add=SYS_ADMIN

Let's find the best way for this use case which would be compatible with the test steps approach.

**Comment by psss** [comment]
Here's some brainstorm. The default "full" syntax for this could be:

    tmt provision --how=podman --image=fedora:rawhide --cap-add=SYS_ADMIN

We could possibly provide the following shortcut as well:

    tmt provision --podman fedora:rawhide --cap-add=SYS_ADMIN

However this would run only the `provision` step, so we would need:

    tmt execute provision --podman fedora:rawhide --cap-add=SYS_ADMIN

Or even include the `discover` step if defined by the testset:

    tmt discover execute provision --podman fedora:rawhide --cap-add=SYS_ADMIN

To `run` all test steps with modifying behaviour of some we could also do:

    tmt run provision --podman fedora:rawhide --cap-add=SYS_ADMIN

Maybe we could even have:

    tmt run --podman fedora:rawhide --cap-add=SYS_ADMIN

Or something like this?

    tmt run --container=fedora:rawhide --cap-add=SYS_ADMIN

What do you think?

**Comment by hroncok** [comment]
tmt run --container=fedora:rawhide --cap-add=SYS_ADMIN

Sounds nice.

**Comment by psss** [comment]
Good. Covered by the `/stories/cli/run/shortcuts/container` story.
