### ISSUE TITLE
execute -h detach can't report timeout for beakerlib tests

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#605]
When `detach` executor runs beakerlib test it doesn't set special value if timeout happened but returns `1` as for any other issue.

With beakerlib-1.25 we can see that `TESTRESULT_STATE="started"` but I think that timeout should be handled by explicit exit value, similar way how it is done for `shell` test (exitcode 124) and how `tmt` executor does it.

To reproduce:
Go to tests/execute/duration/data and `tmt run -a tests --name /test/long/beakerlib execute -h detach`

Resulting exitcode.log (in $workdir/plan/execute/data/test/long/beakerlib):
`1`

Compare with `/test/long/shell` where exitcode.log contains 124 and thus `errr /test/long/shell (timeout)` can be detected

**Comment by pvalena** [comment]
This is only the case for `beakerlib` framework handling- you're right, the error code is overriden (should be simply left as is instead).

https://github.com/psss/tmt/blob/master/tmt/steps/execute/run.sh#L190

I'll prepare a fix.

**Comment by pvalena** [comment]
While we're at it, are there any other special cases?

**Comment by lukaszachy** [comment]
I'm not aware of any other specialities.

**Comment by pvalena** [comment]
Fix prepared in #655.

**Comment by psss** [comment]
Resolved by #655.
