### ISSUE TITLE
tmt should install debuginfo packages in recommends / require via `dnf debuginfo-install`

### ISSUE THREAD

**Issue by thrix** [psss/tmt#624]
This came up in:

https://src.fedoraproject.org/rpms/gdb/pull-request/9

Maybe we should make sure `tmt` is smart enough to know it should install debuginfo packages specially?

**Comment by thrix** [comment]
@psss @lukaszachy what do you think about this?

**Comment by lukaszachy** [comment]
Hm, seems like a nice feature.

**Comment by psss** [comment]
So this means that the `install` prepare plugin would filter all `*.debuginfo` packages and install them using `dnf debuginfo-install`? If that's it I believe the implementation should be easy.

**Comment by lukaszachy** [comment]
Do we support yum? (rhel-7 and older) If so `debuginfo-install` is a way to go and it is provided by either `yum-utils` or `dnf-utils`

**Comment by psss** [comment]
If `debuginfo-install` is the way which would work for both old and new releases, the implemetation should not be difficult, I guess. Shall we consider this for `1.5`?

**Comment by psss** [comment]
The solution should cover all currently supported Fedoras, CentOS and RHEL7+.
