### ISSUE TITLE
Enable a COPR for a test run without specifying a package

### ISSUE THREAD

**Issue by martinpitt** [psss/tmt#647]
For developing tests with packit and GitHub integration like in https://github.com/martinpitt/cockpit/pull/13 , I need to run a test against Fedora plus a COPR.

I tried with 

    tmt run --all prepare --how install --copr packit/martinpitt-cockpit-13

for running tests in [cockpit](https://github.com/cockpit-project/cockpit), but that does not actually enable the COPR -- there is no copr repo in /etc/yum.repos.d/, and all installed packages are from Fedora proper.

According to the [documentation](https://docs.fedoraproject.org/en-US/ci/tmt/#_prepare_options), I can explicitly install a package from a COPR with e.g.

    tmt run --all prepare --how install --copr packit/martinpitt-cockpit-13 --package cockpit-system

and *that* seems to enable the COPR repo *permanently* -- i.e. all *other* packages that the test plan wants to install are then also installed from that COPR.

I think that's a bit unintuitive -- either the COPR should be enabled globally (and then not require a `--package`), or the copr *only* applies to that particular package (not sure if there is an use case for it).

So, specifying "any package" is certainly a good enough workaround, but IMHO that could be a little cleaner. In particular, when trying to document `tmt` commands generically -- the packages to install ought to be in the FMF test plan, not repeated in command lines.

Thank you!

testcloud-0.4.0-6.fc33.noarch
tmt-1.3.1-2.fc33.noarch

**Comment by psss** [comment]
Thanks for describing the issue in detail. 

> I think that's a bit unintuitive -- either the COPR should be enabled globally (and then not require a `--package`), or the copr _only_ applies to that particular package (not sure if there is an use case for it).

Yes, agreed. My expectation would be that the `--package` should not be required to enable a copr repo and I don't see a use case for enabling the repo only for that particular package. Seems like an easy fix we could try to squeeze into `1.4`.

**Comment by martinpitt** [comment]
@psss: I think that `--package` does not actually relate to `--copr` at all -- I can specify only `--package` to install an additional one (which is not part of the test plan). So it rather just seems like a bug, not a design decision, that --package somehow "enables" processing of --copr ?

**Comment by psss** [comment]
Yes, precisely, just a bug in the implementation.
