### ISSUE TITLE
tmt run execute should display some progress bar of test execution by default

### ISSUE THREAD

**Issue by jscotka** [psss/tmt#662]
When execution big test suite with long test time. I found the UI issue, basic output is good for short test execution, but not for long ones with verbose test output.

I have trouble finding where I'm and how many tests were already executed (and it is not easy to find it via parsing `log.txt`)
I can imagine some progress bar like: 
```
 $ tmt run -a provision -h minute -i 1MT-RHEL-8.5.0-20210316.n.0 test --name /Sanity/selenium-internal
/var/tmp/tmt/run-006

/plans/default
...
    execute
        how: tmt
        (1/53) /Sanity/selenium-internal/current/test/node
```
maybe via some `sys.stderr.write(f"\r\t\t\t({current}/{total}) {test.node.id}")`  possible somewhere inside `tmt/steps/execute/internal.py`?

I can imagine also a solution without any `\r` escape char, and print each test for each line (and also display if it passed of failed) could be good to find that there is some error earlier when debugging and start to investigate it.

I know that there is `verbose` and `debug` mode, but I want just this info.  and verbose and debug does not fit my usecase anyway. `verbose` mode is more less suitable, but this could be default behaviour

Maybe also there could be option like in `pytest` `-x` what stop execution after first fail. Especially when fixing some issue in library, it affect all cases not just one.

Solution could be also some post-processing like existing `tmt run -i run-006 --follow` I can imagine also something like `tmt run -i run-006` options what could process output dir and show the info for me.
 - ` --progress` will show current progress (already executed tests with failed ones)
 - `--show-failed` will show failed testcases in the run id

**Comment by psss** [comment]
So the main difference from the `verbose` output (which already lists individual tests) is to provide the precentage of completion? Would something like this cover your use case?

```
    execute
        how: tmt
            00:00:04 /tests/core/adjust (1/3)
            00:00:02 /tests/core/docs (2/3)
            00:00:12 /tests/core/dry (3/3)
```

Exit after the first failure seems like a useful feature. Perhaps it would make sense to track it under a separate issue?

**Comment by jscotka** [comment]
@psss yes, exit after first value probably I could make as separate issue, it makesense. 
difference from `verbose` mode is, that verbose shows more information, e.g. list of tests at the beginning. what Is not so useful and in case of tens(hundreds) of tests does not make sense to display them for me, but totally acceptable inside verbose mode

So this could be about default behaviour. That also inside default not verbose mode it could display some progress.

**Comment by jscotka** [comment]
created separate issue for exit after first fail (https://github.com/psss/tmt/issues/663)

**Comment by psss** [comment]
@FrNecas, so the check for an attached terminal [seems](https://stackoverflow.com/questions/1077113/how-do-i-detect-whether-sys-stdout-is-attached-to-terminal-or-not) to be easy:

```python
if sys.stdout.isatty():
    do something
```

**Comment by FrNecas** [comment]
Nice, thanks. I will work on this one, just a quick write-up of what was agreed on at hacking session today:
 - keep verbose as it is (perhaps add numbering of the tests)
 - if not verbose/debug and terminal is connected, show a "status bar" using `\r`, something like `\r(<test index>/<number of tests>) <test name>`.
