### ISSUE TITLE
RFE: TMT run should have option to to exit after first fail

### ISSUE THREAD

**Issue by jscotka** [psss/tmt#663]
When debugging bigger testsuite it is useful to fail fast and exit running after first failed test. Especially when tweaking also some library used by more tests.

e.g. same  behaviour what provides `pytest` `-x` option

**Comment by FrNecas** [comment]
@adka1408 would you be interested to take a look into this now that the reboot PR is finished? Should be quite simple to implement. Also an issue that is slightly related that you could work on (probably a bit more complicated than this one) - https://github.com/psss/tmt/issues/519

**Comment by adka1408** [comment]
@FrNecas yes, I will take a look on that.
