### ISSUE TITLE
As a tester/developer, I want to be notified if the test conversion was not complete.

### ISSUE THREAD

**Issue by milosmalik** [psss/tmt#665]
Very often Makefiles contain commands which are executed before `runtest.sh` is executed. These commands are not converted when `tmt test import` is called. These commands should be either copied into the Setup phase in `runtest.sh` or there should be a warning that something was skipped during conversion.

**Comment by psss** [comment]
Raised on the stakeholder meeting as one of the issues blocking complete removal of `Makefile` metadata. Let's try to address this in `1.5`.

**Comment by lukaszachy** [comment]
@milosmalik Do you have some examples, please?

**Comment by milosmalik** [comment]
https://src.fedoraproject.org/tests/selinux/blob/main/f/checkpolicy/sedispol
https://src.fedoraproject.org/tests/selinux/blob/main/f/checkpolicy/sedismod

There is a `chmod` command in both `Makefiles` which makes the `sedispol.exp` or `sedismod.exp` files executable.
When I used the `tmt test import` command, the TCs were converted but failed because the `*.exp` scripts were not executable.
