### ISSUE TITLE
Export text fields of a case to nitrate should be checked by lint for compliance with the specification

### ISSUE THREAD

**Issue by dkarpele** [psss/tmt#692]
This issue was created after discussion in https://github.com/psss/tmt/pull/641#discussion_r603061137
[Spec](https://tmt.readthedocs.io/en/latest/spec/tests.html#manual)

1. `tmt test lint` should check If the format of `test.md` respects the specification. Probably we can add a list of allowed headers for export operation and if `test.md` has headers not from the list -> print a warn.
2. Call `tmt test lint` during export of `test.md` (???) and probably print a warning, e.g. `Invalid level 3 header 'Expect'`

**Comment by psss** [comment]
Covered by #699.
