### ISSUE TITLE
Include support for exploring L1 and L2 metadata

### ISSUE THREAD

**Issue by psss** [psss/tmt#7]
During recent discussion it was raised that the tool should support an easy way how to explore L1 and L2 metadata. For example hide unnecessary implementation details such as that testsets are identified by the `execute` keyword so instead of user learning this and doing:

    fmf --key execute

there should be a more straighforward way to do this directly using `tmt`, for example:

    tmt testset --list

Similarly there should be a `test` subcommand supporting L1 metadata investigation:

    tmt test --list

**Comment by lukaszachy** [comment]
Can't we use 'testsuite' instead of testset?

**Comment by psss** [comment]
The `test` subcommand should probably support creating new test skeleton as well:

    tmt test --create --template xyz

This would obsolete `beaker-wizard`.

**Comment by psss** [comment]
> Can't we use 'testsuite' instead of testset? I believe testsuite is a common name with clear meaning.

We've already had a discussion about this when putting together the specification. Testset was the winner. I think one of the arguments was to make it clearly different from testsuites which are already used and mean something else. I would stick with that as IMO the idea of `testset` is something new and different. Using a dedicated term for this should cause less confusion. And of course, the main advantage: It's a palindrom! :-)

**Comment by psss** [comment]
Basic set of commands for L1 and L2 metadata exploration implemented:

    tmt test ls [regex]
    tmt test show [regex]
    tmt plan ls [regex]
    tmt plan show [regex]
    tmt story ls [regex]
    tmt story show [regex]

In addition, stories can be filtered by coverage:

    > tmt story ls --help
    Usage: tmt story ls [OPTIONS] [REGEXP]...

    List available stories.

    Options:
    -i, --implemented  Implemented stories only.
    -t, --tested       Tested stories only.
    -d, --documented   Documented stories only.
    -c, --covered      Covered stories only.
    -u, --uncovered    Uncovered stories only.
    --unimplemented    Unimplemented stories only.
    --untested         Untested stories only.
    --undocumented     Undocumented stories only.

Current coverage for `ls` and `show` can be displayed in this way:

    > tmt story coverage ls show
    code test docs story
    done done todo /stories/cli/plan/ls
    done todo todo /stories/cli/plan/show
    done done todo /stories/cli/story/ls
    done todo todo /stories/cli/story/show
    done done todo /stories/cli/test/ls
    done todo todo /stories/cli/test/show
    100%  50%   0% from 6 stories

Closing as done.
