### ISSUE TITLE
ftff4

### ISSUE THREAD

**Issue by martinky82** [psss/tmt#709]

**Comment by martinky82** [comment]
Sorry. This issue was crated by a toddler while I left mycompouter for a minute unattended... ;)

**Comment by psss** [comment]
Sending congrats for the very first issue! ;-)

**Comment by martinky82** [comment]
I will convey the message :)

**Comment by pvalena** [comment]
Great! Needs a bit work on the description though :).

**Comment by psss** [comment]
Yeah, there is still some space for improvement for the summary as well:

> It is challenging to be both concise and descriptive, but that is what a well-written [summary](https://tmt.readthedocs.io/en/latest/contribute.html#commits) should do.

The "concise" part is well covered already, the descriptive aspect could be improved a bit ;-)
