### ISSUE TITLE
`tmt test lint` does not accept all valid attributes

### ISSUE THREAD

**Issue by stepnem** [psss/tmt#718]
Problem introduced by commit 5d8c146586ac.

Steps to reproduce (from inside the tmt git repository):

```shell
tmt test lint | grep fail
```
Output:
```text
fail unknown attribute 'coverage' is used
fail unknown attribute 'adjust' is used
fail unknown attribute 'adjust' is used
```

**Comment by psss** [comment]
Thanks for filing the issue. The `coverage` key is not included in the L1 metadata [specification](https://tmt.readthedocs.io/en/latest/spec/tests.html). Why do you think it should be supported? Perhaps you are using it for use cases now covered by the new [link](https://tmt.readthedocs.io/en/latest/spec/core.html#link) key?

Regarding the `adjust` key: There has been a change in the `fmf` implementation which means that after applying the rules the `adjust` key is not remove from the metadata node. So I guess we could now include it among the core (L0) attributes.

@lukaszachy, @jscotka, what do you think?

**Comment by stepnem** [comment]
Thank you for the response.

I don't use the `coverage` attribute myself; I originally noticed the problem with `adjust` (in tests produced by `tmt import` (importing Nitrate relevance)) and only used tmt's own tests to illustrate the problem in a simply reproducible way.

I can't comment on the implementation, but find it surprising that tmt's own tests don't pass lint. Is the `coverage` usage there mistaken?

`adjust` is documented as working, so should definitely be supported as far as I understand.

**Comment by psss** [comment]
> I can't comment on the implementation, but find it surprising that tmt's own tests don't pass lint.

Good point! :) We should ensure that all `tmt` tests are nice & clean. The `coverage` attribute was an experimental example (before `link` key was introduced) and thus should be removed.

**Comment by lukaszachy** [comment]
Cool. tmt lInt is finally becoming useful. Just specification isn't up-to-date

> Thanks for filing the issue. The `coverage` key is not included in the L1 metadata [specification](https://tmt.readthedocs.io/en/latest/spec/tests.html). Why do you think it should be supported? Perhaps you are using it for use cases now covered by the new [link](https://tmt.readthedocs.io/en/latest/spec/core.html#link) key?

Isn't this candidate for `lint --fix`? Similar to relevancy -> adjust conversion.

> 
> Regarding the `adjust` key: There has been a change in the `fmf` implementation which means that after applying the rules the `adjust` key is not remove from the metadata node. So I guess we could now include it among the core (L0) attributes.

Let's make it core (L0) attribute.

**Comment by lukaszachy** [comment]
@psss I'm not so sure about 'adjust'. If I add it to Test._keys it spoils show() a bit 
```
      adjust {'environment': {'METHODS': 'container local'}, 'when': 'trigger == commit'}
             {'environment': {'METHODS': 'container local virtual'}, 'when': 'how == full'}
```
I'd prefer to fix lint part now and decide how to proceed with #636 in the future.

**Comment by psss** [comment]
> I'd prefer to fix lint part now and decide how to proceed with #636 in the future.

Yeah, that makes perfect sense to me.

> Isn't this candidate for `lint --fix`? Similar to relevancy -> adjust conversion.

No, the `coverage` attribute was really just a future dream example. Let's remove it.
