### ISSUE TITLE
Missing recommend causes an error for rhel7 guest

### ISSUE THREAD

**Issue by sopos** [psss/tmt#734]
if a package listed in `recommend` is missing, tmt ends up with an error in _prepare_ step if the guest system is rhel7
rhel8 is ok

**Comment by lukaszachy** [comment]
rhel7: rpm -q --whatprovides "FOOOO" || yum --skip-broken install -y "FOOOO" && rpm -q --whatprovides "FOOOO"
rhel8: rpm -q --whatprovides "FOOOO" || dnf --skip-broken install -y "FOOOO"

IMHO  this was introduced with 218307b8b7ebec5fcfa2666e31a7816d4e869d6c

Do we test prepare against yum guests? (or prepare at all?)

**Comment by sopos** [comment]
I was running https://github.com/RedHat-SP-Security/tests/blob/sopos-rsyslog-RELP-system-role/rsyslog/Multihost/relp/direct-config.fmf on rhel-7.9

**Comment by lukaszachy** [comment]
[Specification](https://tmt.readthedocs.io/en/stable/spec/tests.html#recommend) says for `recommend` attribute:
> As a tester I want to specify additional packages which should be installed on the system if available and no error should be reported if they cannot be installed.

So even silly example as this should pass (and indeed it passes for dnf case)
```
test: /usr/bin/true
recommend: "FOO-impossible"
```

**Comment by sopos** [comment]
I guess the line https://github.com/psss/tmt/blob/218307b8b7ebec5fcfa2666e31a7816d4e869d6c/tmt/steps/prepare/install.py#L219 should not start with `&&` but with `||`

**Comment by lukaszachy** [comment]
IMHO tmt shouldn't check anything for `recommend` or have final `|| true` for check to always succeed (so it is just an info about what was (not)installed)

**Comment by sopos** [comment]
Right, my previous proposal should apply to _require_.
I'm not sure what the referenced line handle, after all. :-(

**Comment by sopos** [comment]
But the previous issue wan maybe about yum returning 0 even if some packages failed. Thus `;` might be better for _require_ and `; true` for _recommend_.

**Comment by psss** [comment]
I don't think we need the extra `true` for recommend. The general idea behind `missing: skip` is basically to enable `--skip-broken`. I think it still might make sense to report issues when there is for example a network outage or broken repository. Should be fixed by #741 which also extends the test a bit.
