### ISSUE TITLE
TODO: verbosity vs debug changes

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#76]
# provision
 - smallcaps
 - run command: indent
## verbose
 - box ++
 - vagrantfile --
 - Trying to enable: QEMU user session --

## debug

# prepare
 - run command: indent
## verbose
 - how: ??
 - action: ?? # adding playbook etc
## debug
 - Adding into Vagrantfile -> yellow

**Comment by psss** [comment]
Most of the `provision` and `prepare` output inconsistencies covered by #218.

**Comment by pvalena** [comment]
Not for Vagrant, but as this was just a note for me, I'm fine with keeping it closed (I'll get back to this when converting the plugin).
