### ISSUE TITLE
Option to ignore existing plans and for the default one

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#764]
UC: I'm in a repo with a lot of plans (eg. tmt itself) and I'm developing (new) test.  I want to run this test using command line options in the same way as if there was no plan in the repo.

It would by much easier to e.g. `tmt run --default ` instead of messing up with the plan structure. 

Current possibilities are
1. Delete all plan definitions (easiest to do but potential problem in future git commits)
2. Pick one plan and modify its steps via cmdline
3. Create new "empty" plan and use it as in step 2. (potential problem with adding into git by mistake)

**Comment by psss** [comment]
Yes, this definitely makes sense and should be easy to implement. Regarding current options, executing a single test should work:

    tmt run test -n smoke

Any plan which does not have the requested test is skipped:

```
/var/tmp/tmt/run-004

/plans/features/advanced
    discover
        how: fmf
        directory: /home/psss/git/tmt
        filter: tier: 3
        names: smoke
        summary: 0 tests selected
        warning: No tests found, finishing plan.
```

But yes, the output can be unnecessarily long. So the following is probably a better option:

    tmt run plan -n core test -n smoke

Should the new option go directly under the `run` subcommand or shall we rather add it to the `plans` subcommand as it is related to "picking" plans? The second variant would look like this:

    tmt run plan --default

**Comment by FrNecas** [comment]
+1 on this idea, this is something I've sometimes struggle with too (e.g. I was writing a test for `tmt clean` and I had to check which plan to run in order to run the test easily). Even though `tmt run --default` is shorter, "default" run doesn't make much sense and hence it would IMHO make more sense to include it under the `plan` subcommand.
