### ISSUE TITLE
Hardware requirements and units

### ISSUE THREAD

**Issue by happz** [psss/tmt#768]
What units does TMT community want to support/use?

```yaml
memory: "4 GB"
memory: "4 GiB"
```

While more common, "GB" is technically not correct (AFAICT) when used for multiplies of 1024 (which I do pretty much always...). So, the question is, what units TMT is going to support, recommend, endorse, etc.?

While working on the implementation, units appear everywhere. I'm going to depend on https://pint.readthedocs.io/en/stable/ library to handle and convert them, and personally, I'd prefer to use correct units as much as possible, i.e. "GiB" for 2^32, 4294967296.

**Comment by psss** [comment]
I would agree with @happz here: I believe it's always good to prevent confusion and make the naming clear and unambiguous. The unfortunate situation with the MB/GB collision does not give much choice really, but I'd say the standard (decimal) prefixes have been reserved first so... kdo dřív přijde, ten dřív mele ;-)

**Comment by psss** [comment]
Perhaps one more note to clarify the expectations: I would recommend to support both decimal and binary prefixes, so that user can choose `1 MB` for `1 000 000 B` and `1 MiB` for `1048576 B`.

**Comment by thrix** [comment]
Yeah, I would say that we want to be correct here technically. If somebody says 4GB, it will be x1000s .... and if the cloud expects 4GiB the library @happz is working on will make sure it is converted ... I hope the Pint package we are now using there will help in this conversion

**Comment by happz** [comment]
> Perhaps one more note to clarify the expectations: I would recommend to support both decimal and binary prefixes, so that user can choose `1 MB` for `1 000 000 B` and `1 MiB` for `1 048 576 B`.

Definitely, there's no reason to support one set of units and ignore the other. Internally, I plan to rely on [Pint](https://pint.readthedocs.io/en/stable/) entirely, to do the parsing and conversions, because... Well, why should I invent the wheel? :)

```python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>>
>>>
>>> ureg('4 GB')
<Quantity(4, 'gigabyte')>
>>>
>>> ureg('4 GB').to('bytes')
<Quantity(4e+09, 'byte')>
>>>
>>> ureg('4 GiB').to('bytes')
<Quantity(4.2949673e+09, 'byte')>
>>>
>>> ureg('4 GiB').to('MiB')
<Quantity(4096.0, 'mebibyte')>
>>>
>>> ureg('4 GiB').to('MB')
<Quantity(4294.9673, 'megabyte')>
>>>
>>> ureg('4 GiB').to('MiB').magnitude
4096.0
>>>

# Does a provisioning plugin expect the disk size to be specified in MiB? Sure, no problem:
>>> read_from_spec = '40 GiB'
>>>
>>> f"--disk-size={int(ureg(read_from_spec).to('MiB').magnitude)}"
'--disk-size=40960'
>>>
```

Can't be easier, and I'm pretty sure I wouldn't write anything that simple to use :) So, yeah, my plan definitely includes support for both variants. I would have to actually actively work to *disable* one of them :)

There seems to be an agreement - or, at least, no opposition so far - that preserving their true meanings is the way to go, I'll proceed with my work then.

Please, let me know if there any other aspects that shouldn't be overlooked.

**Comment by psss** [comment]
Looks nice! Thanks a lot for working on this. Maybe just one thing: I've noticed the `python3-pint` package is not available in the `epel-8` repository. We should make sure we have all dependencies for `centos-8` and `rhel-8` as well.

**Comment by thrix** [comment]
@psss will reach out to devel if we could add it to epel

**Comment by thrix** [comment]
```
06:01 < mvadkert> lbalhar: ciao, I am seeking some Python advice
06:02 < mvadkert> lbalhar: we are finding out we need to get python-pint to epel-8
06:02 < mvadkert> lbalhar: https://src.fedoraproject.org/rpms/python-pint
06:02 < mvadkert> lbalhar: I wonder, what is the easiest way to get it there, try to get it working in copr and then ask the maintainer?
06:06 < lbalhar> mvadkert, basically yes, you can rebuild it in copr or koji and see, if it works and maintainer is willing to take care of it in epel, it's easy, otherwise, you can be a maintainer only for epel
06:07 < mvadkert> ah cool, did not know I can be a maintainer only in epel
```

**Comment by thrix** [comment]
trying to build in copr now ...

**Comment by happz** [comment]
> Looks nice! Thanks a lot for working on this. Maybe just one thing: I've noticed the `python3-pint` package is not available in the `epel-8` repository. We should make sure we have all dependencies for `centos-8` and `rhel-8` as well.

Aha, that's quite an important detail, I did not realize this could be a problem. In my world, everyone - me... - just happily installs to virtualenvs...


> @psss will reach out to maintainer if we could add it to epel

Thanks, that was quick.

**Comment by sopos** [comment]
Many tools, e.g. `dd` or `fdisk`, use just _G_ or _M_ to express _GiB_ or _MiB_ respectively.
This is also close to people's thinking, like _machine with 4 gigs of RAM_, meaning `memory: 4G`.

**Comment by happz** [comment]
> Many tools, e.g. `dd` or `fdisk`, use just _G_ or _M_ to express _GiB_ or _MiB_ respectively.
> This is also close to people's thinking, like _machine with 4 gigs of RAM_, meaning `memory: 4G`.

True, true. Despite one could be "liberal in what one accepts from others", I, for one, am not really fond of supporting `G` or `M` in this meaning. Yes, it is possible to infer the actual units, but I would rather stick to using those units from the beginning. Being explicit is a bigger benefit from my point of view.

**Comment by psss** [comment]
I would agree here with @happz, it's one of my favorite rules from `python -mthis`:

> Explicit is better than implicit.
