### ISSUE TITLE
Reboot machine from cmdline

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#775]
Use case: tmt provisioned machine and it has to be rebooted (e.g. stopped responding). Makes sense only for external machines (VMs, openstack, Beaker...)

**Comment by RHEmployee** [comment]
@psss  Hi. I talked with @lukaszachy  and this seems to be free. Would you please assign it to me?
Or is here different approach how to assign tasks? :)

**Comment by psss** [comment]
Ok, assigned to you. Could we start with describing the expected functionality in a bit more detail? How exactly should this work? Is this somehow related to #281 as well or a completely separate feature?

**Comment by RHEmployee** [comment]
Hello.

I think it's can be used in provision step in cases:
minutetip machines (open stack)
local virtual machines (libvirt?)

Beaker machines should be covered either but I'm not sure how this works (I need to look at some beaker api).

Basic functionality should looks like add 2 cli options to provision step. For example:
--reset - soft reboot - just tell OS about shutdown even (usually via ACPI). This expect that OS works and there is no kernel panic for example.
--reset-hard - just let hypervisor known about reboot - hard reboot means that there can be loss of data and OS or network can be in down/broken state.

After some investigation, implementation should look a like:
class tmt.steps.provision.ProvisionPlugin should provide 2 methods for later overload:
def reboot_soft()
def reboot_hard()

In case of minute plugin which should be implemented:
reboot_soft() method just calls prepared http API - this API just instrument openstack to reboot.
same situation is with reboot_hard() method.
For reboot we need to know instantiation name in minute provision step case or similar machine identification which brings some questions like: should we hold list of provisioned machines? 1minutetip works this way. 1minutetip just holds list of provisioned machines but it can be fragile in some ways.
But it looks like tmt already holds needed information so it should be fine. Or not? :)

How it's related to: https://github.com/psss/tmt/issues/281 ?
Issue just mention reboot within test which means: from inside working OS and with some test related magic (count of reboots for example). Reboot can be invoked within test via rhts-reboot which can just call reboot/shutdown -r or switch init number whatever.
I don't think that https://github.com/psss/tmt/issues/281 is related to this issue.
This issue mentions reboot outside of test environment without any help of test.

**Comment by psss** [comment]
As mentioned in #281 I would suggest a single method:

> Just a short note to today's discussion: Instead of introducing two new methods of the `Guest` class I would suggest to add a single method `Guest.reboot()` which would have an optional parametr `Guest.reboot(hard=True)` for hard restart.

> But it looks like tmt already holds needed information so it should be fine. Or not? :)

Yes, information about provisioned guests should be already available. It is stored in `guests.yaml` under the provision workdir so that subsequent runs can use it as well.

>  I don't think that #281 is related to this issue. This issue mentions reboot outside of test environment without any help of test.

But I'd say the new reboot methods will be used for both rebooting guest from inside the test and the command line as well.

**Comment by FrNecas** [comment]
Yes, that's the way I see it too. I feel like that the `reboot` method should be implemented in the `Guest` class (and its subclasses) and also probably in `ProvisionPlugin`'s subclasses which will just call the method of guest. The reboot during test will call the guest method to reboot (not sure which type of reboot, whether soft or hard)

**Comment by RHEmployee** [comment]
> Yes, that's the way I see it too. I feel like that the `reboot` method should be implemented in the `Guest` class (and its subclasses) and also probably in `ProvisionPlugin`'s subclasses which will just call the method of guest. The reboot during test will call the guest method to reboot (not sure which type of reboot, whether soft or hard)

Reboot during test should call and always call soft reboot. If there is something broken, then you need to investigate why machine is not able to reboot itself.

Another question is: do we really need best option? What means that: reboot failed?
Do we have some use cases? I don't have any in top of my head but I can be blind :).

**Comment by psss** [comment]
I'm not sure what would be the best way to handle reboots for containers, as there's no `reboot` supported:

```
# reboot
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Failed to talk to init daemon.
```

Perhaps for them the `how="best"` option could be useful. Or for containers we could implement both `soft` and `hard` as container stop and start. Thoughts?

**Comment by RHEmployee** [comment]
> I'm not sure what would be the best way to handle reboots for containers, as there's no `reboot` supported:
> 
> ```
> # reboot
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> Failed to talk to init daemon.
> ```
> 
> Perhaps for them the `how="best"` option could be useful. Or for containers we could implement both `soft` and `hard` as container stop and start. Thoughts?

I think that this bug is about reboot from cmdline not within container.
If you have container and you can use podman, then you can reboot machine from outside similary as minute plugin instruments openstack.

However, reboot from inside can be tricky how it looks.

**Comment by mrc0mmand** [comment]
> I'm not sure what would be the best way to handle reboots for containers, as there's no `reboot` supported:
> 
> ```
> # reboot
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> Failed to talk to init daemon.
> ```
> 
> Perhaps for them the `how="best"` option could be useful. Or for containers we could implement both `soft` and `hard` as container stop and start. Thoughts?

This is expected, `reboot` is nowadays a symlink to `systemctl` which then uses dbus to send the `reboot` action. So, if the container runs as a *standard* container (i.e. without PID 1), reboot from within the container won't work. In such cases you have to invoke `podman restart <container-id>` from the outside.

**Comment by psss** [comment]
Well, I believe the reboot functinality for containers could still be useful. Imagine you have a process which got stuck in the container and eats a lot of cpu. IMO there should be an easy (and generic) way to reboot as any other guest implementation we have (except for `local` which is very "special"). I'd suggest to first finalize #794 as the first step and then dive into reboot from command line and test.

**Comment by psss** [comment]
Covered by #794.
