### ISSUE TITLE
Simplify multiple debug/verbose options

### ISSUE THREAD

**Issue by psss** [psss/tmt#783]
As suggested in https://github.com/pallets/click/issues/1891 let's use `count=True` instead of `multiple=True, is_flag=True` for the `--verbose` and `--debug` options. A corresponding adjustment of `Common.opt()` will be needed as well. Should be fairly easy.

**Comment by RHEmployee** [comment]
@psss 
Hi. Is this free to take? :)

**Comment by psss** [comment]
No assignee, no comment about looking into the issue --> it's yours :)

**Comment by RHEmployee** [comment]
Hello.

There is first version of proposed changes. Looks like only --verbose and --debug are affected.
https://github.com/psss/tmt/pull/791
