### ISSUE TITLE
Provision using connect fails with the smoke plan

### ISSUE THREAD

**Issue by psss** [psss/tmt#81]
I'm using the following command line to run the `/plans/smoke` plan against a running box:

    tmt run --debug --all provision --how connect --user root --guest 1.2.3.4 --key /home/psss/.ssh/private_key plan --name smoke

The `execute` step ends up with the following error:

    Run command 'vagrant rsync'.
    Run command 'vagrant ssh -c nohup /var/tmp/tmt/run-568/plans/smoke/execute/run.sh -v /var/tmp/tmt/run-568/plans/smoke shell /var/tmp/tmt/run-568/plans/smoke/execute/stdout.log /var/tmp/tmt/run-568/plans/smoke/execute/stderr.log'.
    out: nohup: vstup ignoruji a výstup připojuji k 'nohup.out'
    err: Connection to 1.2.3.4 closed.
    out: nohup: spuštění příkazu '/var/tmp/tmt/run-568/plans/smoke/execute/run.sh' selhalo: No such file or directory
    Run command 'bash -c "vagrant plugin list | grep '^vagrant-rsync-back '"'.
    out: vagrant-rsync-back (0.0.1, global)
    Run command 'vagrant rsync-back'.
    out: ==> default: Rsyncing folder: /var/tmp/tmt/run-568/plans/smoke/ => /var/tmp/tmt/run-568/plans/smoke
    err: There was an error when attempting to rsync a synced folder.
    err: Please inspect the error message below for more info.
    err
    err: Host path: /var/tmp/tmt/run-568/plans/smoke
    err: Guest path: /var/tmp/tmt/run-568/plans/smoke/
    err: Command: rsync --verbose --archive --delete -z -e ssh -p 22 -o StrictHostKeyChecking=no -i '/home/psss/.ssh/private_key' --exclude .vagrant/ root@1.2.3.4:/var/tmp/tmt/run-568/plans/smoke/ /var/tmp/tmt/run-568/plans/smoke
    err: Error: rsync: change_dir "/var/tmp/tmt/run-568/plans/smoke" failed: No such file or directory (2)
    err: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1659) [Receiver=3.1.3]
    err: rsync: [Receiver] write error: Broken pipe (32)

Works fine for the other two plans. @pvalena, could you please have a look?

**Comment by pvalena** [comment]
Interesting, rsync crashes ?! /me checks

**Comment by psss** [comment]
Vagrant is not used for syncing anymore.
