### ISSUE TITLE
Document how to migrate tests from `STI` to `tmt`

### ISSUE THREAD

**Issue by psss** [psss/tmt#815]
It would be good to provide a concise list of steps needed to convert `STI` tests to `tmt`. This would help new users of `tmt` get quickly started. I'd suggest to mention at least the following two scenarios:

* A (single) custom shell script execution (basically the `tmt init -t mini` scenario)
* Migrating beakerlib tests (covered by `tmt test import` and `tmt plan create -t base`)

It might make sense to mention required packages handling as well. As far as location is concerned, what about adding a new "How do I convert an STI test to tmt?" section to the [questions](https://tmt.readthedocs.io/en/latest/questions.html)?

**Comment by mike-fabian** [comment]
This  simple example psss made was very helpful: 

https://src.fedoraproject.org/rpms/ibus-m17n/c/88d0a1f9939cb93b147fd758e4647cf366ce6926?branch=rawhide

**Comment by thrix** [comment]
Sounds like a plan to me! Glad to see this happening

**Comment by psss** [comment]
A couple of relevant links:

* https://docs.fedoraproject.org/en-US/ci/standard-test-roles/
* https://docs.fedoraproject.org/en-US/ci/tests/
* https://tmt.readthedocs.io/en/latest/questions.html
* https://tmt.readthedocs.io/en/stable/spec/plans.html#shell
* https://tmt.readthedocs.io/en/stable/spec/plans.html#install

**Comment by psss** [comment]
@ZelenyMartin is interested to put together the docs. Martin, do you plan to look into this today/tomorrow or shall we move the issue to the next milestone?
