### ISSUE TITLE
RFE: Add timestamps to the tmt debug output

### ISSUE THREAD

**Issue by bocekm** [psss/tmt#821]
Reason: There's a limit of 5 minutes for a test duration (https://tmt.readthedocs.io/en/stable/spec/tests.html#duration). But this limit applies to the _execute_ step of the tmt run only. Yet currently, for the lack of timestamps in the tmt output, it's not easy to find out how much time the execute step consumes.

@psss suggests to add the timestamp around this line: https://github.com/psss/tmt/blob/master/tmt/utils.py#L236.

**Comment by psss** [comment]
As far as the format is concerned, I'd suggest something short & nice, perhaps a UTC timestamp like this?

```python
>>> datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
'2021-06-30 08:16:31'
```

Or, perhaps, adding the time part only would be just enough for most use cases?

```python
>>> datetime.datetime.utcnow().strftime('%H:%M:%S')
'08:17:37'
```

**Comment by psss** [comment]
@adka1408, would you be interested to look into this?

**Comment by adka1408** [comment]
> @adka1408, would you be interested to look into this?

@psss Yes, I will take a look.
