### ISSUE TITLE
For url based environment-file we need a possiblity to set custom tls certificate location

### ISSUE THREAD

**Issue by zhukovgreen** [psss/tmt#852]
In convert2rhel the source of env vars located in domain with custom TLS certificate. We need a possibility to provide the path to the certificate.

Design proposal:
```yaml
        environment-file:
            - ".env"
            - ".env.yaml"
            - {"url": "https://gitlab.cee.redhat.com/oamg/convert2rhel/convert2rhel-secrets/-/raw/main/.env", "cert_path": "./ca_certs/ca.crt"}
            - "https://raw.githubusercontent.com/psss/tmt/22a46a4a6760517e3eadbbff0c9bebdb95442760/tests/core/env/data/vars.yaml"
```

Solution should be simple:
- forward the path to the tls certificate on request.get at this line https://github.com/psss/tmt/blob/b67ccf5f73ca093dea8ce35af42e6c9e3351ebb9/tmt/utils.py#L772

```diff
-            content = requests.get(env_file).text
+            content = requests.get(env_file, verify=str(Path("to-tls-cert"))).text
```

_Originally posted by @ZhukovGreen in https://github.com/psss/tmt/pull/795#discussion_r679214771_

**Comment by ZhukovGreen** [comment]
We had a discussion with @bocekm and agree he is going to test our https://github.com/oamg/convert2rhel/pull/321/files#diff-5ae9adacc9ce4ac4f6d80f8c06e2f4a4967a272f41bc5f2643ed946c4077f685R13 source of secrets with fresh install of tmt via dnf (based on advice from @lukaszachy)

**Comment by bocekm** [comment]
@psss, this is not needed and this issue can be closed. When one installs `tmt` as an rpm from Fedora repos (from PyPI), it is able to pick up the locally installed certificates. That works for us (https://github.com/oamg/convert2rhel/).

**Comment by psss** [comment]
Good, thanks for verifying this!
