### ISSUE TITLE
Imported test metadata should be stored in a reasonable order

### ISSUE THREAD

**Issue by psss** [psss/tmt#86]
Currently `tmt test convert` stores yaml keys in random order. It would be nice to store the information in a way which is pleasant for user to read. For example `summary`, if present, should be the first. Implementation should be [relatively easy](https://stackoverflow.com/questions/31605131/dumping-a-dictionary-to-a-yaml-file-while-preserving-order) using an `OrderedDict`.

The proposed order of the L1 Metadata keys:

* summary
* description
* contact
* test
* path
* duration
* environment
* tag
* tier
* component
* relevancy
* enabled
* result

**Comment by psss** [comment]
@hegerj, this might be an interesting stuff for you.

**Comment by hegerj** [comment]
"Changed in version 3.7: Dictionary order is guaranteed to be insertion order. This behavior was an implementation detail of CPython from 3.6."
https://docs.python.org/3.7/library/stdtypes.html#dict

Should I then bother with `OrderedDict` given the yaml issue?

**Comment by psss** [comment]
Seems the `yaml.dump()` method supports `sort_keys=False` parameter. So the only thing we need is to disable sorting and put the keys in the dictionary in the right order.
