### ISSUE TITLE
Optionally tmt log.txt should have timestamp

### ISSUE THREAD

**Issue by thrix** [psss/tmt#867]
For investigation purposes in CI it would be handy if tmt debug output could be optionally prefixed with timestamp for each line.

**Comment by FrNecas** [comment]
@thrix wasn't this already added by https://github.com/psss/tmt/pull/838 or is the timestamp required somewhere else as well?

**Comment by thrix** [comment]
@FrNecas we would like to see timestamps at each like of log.txt output ...
