### ISSUE TITLE
Document the tmt | wow integration

### ISSUE THREAD

**Issue by psss** [psss/tmt#912]
Would be nice to have an example of how `tmt` can be used together with `wow` without the need of Nitrate:

```
tmt tests export --fmf-id | wow f33 x86_64 --fmf-id - 
```

We've added the feature recently in #845 but haven't documented the use case.

**Comment by lukaszachy** [comment]
Since this is _internal_ tool it is documented internally. Once we upstream wrapper we can document it.
What we could document is intended usage of --fmf-id
