### ISSUE TITLE
Support "test/plan require UEFI" requirement

### ISSUE THREAD

**Issue by happz** [psss/tmt#917]
As suggested in https://gitlab.com/testing-farm/artemis/-/issues/175, one might develop tests that work only with UEFI machines, or machines that do *not* possess this feature. To me, the idea sounds like an HW requirement whose place is in L1/L2 metadata, therefore something for TMT to specify.

No idea where to put this field, whether as a top-level key (`hardware.uefi: true`) or nest it under some key (`hardware.boot.uefi: true`). I guess it makes sense to mention the importance of `uefi: false`, because, once people begin to request UEFI machines, I'm pretty sure they will request machines that absolutely do not, under no circumstances, support UEFI :)

Or as an enum? `hardware.bios: bios|uefi|...`. IIUIC, it's not just about the boot alone, there are other features BIOS/UEFI provide, but maybe `hardware.boot: bios|eufi` would make sense as well.

Anyway, there's a user need, and before implementing the support for it, it would be nice to hear ideas and opinions and get a place in specification.

**Comment by thrix** [comment]
yeah, I like `hardware.boot: bios|uefi` more ... 

Note that also Automotive QE are interested in this, and seems AWS has some support, what is great:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ami-boot.html

**Comment by thrix** [comment]
after discussion, seems it would be good to think about future extensibility, thus:

```
hardware:
    boot:
        method: uefi | bios 
```

So I will open a PR for this. Any mode ideas welcomee

**Comment by fernflower** [comment]
Just for the record - leapp team is also very-very interested in this feature :)

**Comment by pcahyna** [comment]
FYI Fedora images should be now compatible with both firmwares: https://fedoraproject.org/wiki/Changes/FedoraCloudHybridBoot

**Comment by pcahyna** [comment]
```yaml
hardware:
    boot:
        method: uefi | bios 
```
yes, on POWER we will need to select between OpenFirmware and PowerNV (although `boot` may be a bit misnamed, because firmware selection is not just about booting...)

**Comment by psss** [comment]
@pcahyna, so do you suggest to use a better name for the section instead?

**Comment by pcahyna** [comment]
@psss it may be ok after all. I suppose for PowerVM vs. PowerNV one should rather use the hypervisor field, if it is going to exist (like in Beaker, `<hostRequires><system><hypervisor op="==" value=.../></system> </hostRequires>`). At the end, the question is, what is the field going to represent and how it will be used. Let me think whether there is a similar distinction like EFI vs. BIOS on other architectures.

**Comment by psss** [comment]
For the features related to virtualization there is already outlined a `virtualization` section:

```yaml
virtualization:
    is-virtualized: true
    is-supported: false
    hypervisor: kvm
```
