### ISSUE TITLE
[tmt run] Discover step changes tests order

### ISSUE THREAD

**Issue by juk** [psss/tmt#941]
During discover step test order is changed (sorted) compare to the order specified in test plan

$ cat plans/Regression.fmf
summary: Kernel Regression test suite
discover:
    how: fmf
    test: [/kdump/setup-bare-metal,/errata/Regression]
prepare:
    how: ansible
    playbook:
        - playbooks/common.yml
execute:
    how: tmt
report:
    how: display

$ tmt run discover -v plan --name /plans/Regression
/var/tmp/tmt/run-001

/plans/Regression
    discover
        how: fmf
        directory: /home/yk/git1/kernel
        hash: 7a11a0c4ad
        names: /kdump/setup-bare-metal and /errata/Regression
['test']
['/kdump/setup-bare-metal', '/errata/Regression']
        summary: 2 tests selected
            /errata/Regression
            /kdump/setup-bare-metal

**Comment by kkaarreell** [comment]
I want to support this request, this bug prevents me from running keylime tests with tmt (through Packit) as I need setup tasks to be executed first.

**Comment by kkaarreell** [comment]
I think I was able to address my use case using the following patch. Not sure how good approach is this in general.
```
--- /usr/lib/python3.6/site-packages/fmf/base.py.orig	2021-11-18 09:41:20.595994791 +0100
+++ /usr/lib/python3.6/site-packages/fmf/base.py	2021-11-18 09:54:27.747158324 +0100
@@ -519,14 +519,21 @@
         filters = filters or []
         conditions = conditions or []
 
-        for node in self.climb(whole):
+        # first filter all nodes by name, preserving name filter order
+        node_list = []
+        if names:
+            for name in names:
+                for node in self.climb(whole):
+                    if re.search(name, node.name):
+                        node_list.append(node)
+        else:
+            node_list = self.climb(whole)
+
+        # now apply additional filters
+        for node in node_list:
             # Select only nodes with key content
             if not all([key in node.data for key in keys]):
                 continue
-            # Select nodes with name matching regular expression
-            if names and not any(
-                    [re.search(name, node.name) for name in names]):
-                continue
             # Apply filters and conditions if given
             try:
                 if not all([utils.filter(filter, node.data, regexp=True)
```

**Comment by kkaarreell** [comment]
However, the above won't be compatible with the `order` attribute, if it gets supported. OTOH, I can't imagine how my use case would be compatible with the `order` attribute since my test plan is defined by the list of name filters and AFAIK there is no place for the `order` attribute in such listing.

My plan looks like this:
```
summary:
  Tests used by Packit/TFT CI on Github
discover:
  how: fmf
  test: 
   - /setup/configure_tpm_emulator
   - /setup/install_upstream_keylime
   - "/functional/.*"

execute:
    how: tmt
```

**Comment by psss** [comment]
Thanks for providing the patch, @kkaarreell. I don't think it would be a good solution to implement this change in `fmf` as this would introduce a different way how filtering is done by `name` versus by `filter` or `condition`. Also, when there is a non-empty intersection of the name search, fmf nodes appear in the result multiple times. I believe this is not acceptable from `fmf` point of view.

Btw, presence of duplicates is something where we need to clarify expectations from the user point of view first: If the same test name appears in the list of tests to be executed multiple times (or two regexp match the same test), should the test be included (and executed) multiple times?

**Comment by kkaarreell** [comment]
Hi @psss 

> Thanks for providing the patch, @kkaarreell. I don't think it would be a good solution to implement this change in `fmf` as this would introduce a different way how filtering is done by `name` versus by `filter` or `condition`. 

Would you be able to provide an example that would illustrate the difference? I think there would be a difference only in case user would provide multiple name patters. And assuming there would a difference, is this really something that user would not want? 

I believe that currently there is no option how to specify test order withing a plan and therefore listing tests by name seems like a natural approach. 

> Also, when there is a non-empty intersection of the name search, fmf nodes appear in the result multiple times. I believe this is > not acceptable from `fmf` point of view.
> 
> Btw, presence of duplicates is something where we need to clarify expectations from the user point of view first: If the same test name appears in the list of tests to be executed multiple times (or two regexp match the same test), should the test be included (and executed) multiple times?

I think it is perfectly valid to have one test listed multiple times in a test plan. This is something user would to to verify the stability of the test case or eventually for specific scenarios like system update.

**Comment by psss** [comment]
> Would you be able to provide an example that would illustrate the difference?

    fmf ls --name environment --name select

The result of the `fmf.Tree.prune()` method should be a list of tree nodes which match provided filters. It should always be a subset of `fmf.Tree.climb()` and should not contain any duplicates, as it should correspond to a pruned tree.

> I think there would be a difference only in case user would provide multiple name patters. And assuming there would a difference, is this really something that user would not want?

Yes, allowing duplicate nodes would change the current functionality only when multiple names a provided. Still this would be a backward-incompatible change which gives other results then original pruning.

> I believe that currently there is no option how to specify test order withing a plan and therefore listing tests by name seems like a natural approach.

Makes sense but it is related to this specific `tmt` use case. That's why I propose to implement the change in `tmt` rather than `fmf`.

**Comment by psss** [comment]
> However, the above won't be compatible with the `order` attribute, if it gets supported.

Btw, the planned `order` attribute should work fine with the proposed approach: For each test name provided under the `test` attribute, all matching tests would be added to the pile, and each of these batches would be sorted by the `order` stored in test (L1) metadata. I don't see any conflict there.

**Comment by lukaszachy** [comment]
> > However, the above won't be compatible with the `order` attribute, if it gets supported.
> 
> Btw, the planned `order` attribute should work fine with the proposed approach: For each test name provided under the `test` attribute, all matching tests would be added to the pile, and each of these batches would be sorted by the `order` stored in test (L1) metadata. I don't see any conflict there.

IMO the conflict is between ordering by L1's order and enumerating in the 'test' list. Now what should have the final word ;)

**Comment by lukaszachy** [comment]
> Makes sense but it is related to this specific `tmt` use case. That's why I propose to implement the change in `tmt` rather than `fmf`.

+1 - This is tmt 'feature' that you can specify order of tests by enumerating them in discover's 'test' attribute (which would need to be documented)

**Comment by kkaarreell** [comment]
Is it already know how the syntax should look like?

**Comment by psss** [comment]
> Is it already know how the syntax should look like?

See the [order](https://tmt.readthedocs.io/en/latest/spec/core.html#order) attribute as drafted in the spec.

**Comment by psss** [comment]
> IMO the conflict is between ordering by L1's order and enumerating in the 'test' list. Now what should have the final word ;)

I would say test names provided in the `test` attribute would have higher priority: The implementation could look like this:

    tests = []
    for name in test:
       check all discovered tests which match the name regexp
       sort filtered tests by order
       tests.extend(sorted tests)
    return tests

This would allow doing things like:

```yaml
discover:
    how: fmf
    test:
      - /setup/one
      - /features
      - /setup/two
      - /features

Does it make sense? Thoughts?

**Comment by juk** [comment]
> > IMO the conflict is between ordering by L1's order and enumerating in the 'test' list. Now what should have the final word ;)
> 
> I would say test names provided in the `test` attribute would have higher priority: The implementation could look like this:
> 
> This would allow doing things like:
> 
> ```yaml
> discover:
>     how: fmf
>     test:
>       - /setup/one
>       - /features
>       - /setup/two
>       - /features
> 
> Does it make sense? Thoughts?
> ```
Yes, it is a desirable behavior.

**Comment by psss** [comment]
> There is no example in that documentation.I just don't see how the `order` attribute would be listed along with test names in the plan.

The `order` attribute is supposed to be used directly in L1 metadata, that means with other test attributes, e.g. in `main.fmf` of the corresponding test.

**Comment by kkaarreell** [comment]
Having order as an attribute of a test has little use for multiple plans. It would basically prevent you having plans like
```
- testA
- testB
```
and 
```
- testB
- testA
```
I think that the design is too much oriented on automagical test discovery but failing on a plain simple test sequence.

**Comment by psss** [comment]
> Another attempt:
> ...

The second patch looks good to me. Would it make sense to add the support for this under the `_filters_conditions()` method so that selection by name works the same across tests, plans and stories?

**Comment by psss** [comment]
> Having order as an attribute of a test has little use for multiple plans.

Yes, this does not work if/when each plan needs a different test order. On the other hand still can be useful to provide the default test order in a single repo. For example running quick smoke test first together with the `--exit-first` option.

**Comment by kkaarreell** [comment]
Third attempt allowing also duplicate tests enabling run one test multiple times, e.g.
```
tests:
- testA
- testB
- testA
```

```
# diff -u /usr/lib/python3.6/site-packages/tmt/base.py /usr/lib/python3.6/site-packages/tmt/base.py.new2
--- /usr/lib/python3.6/site-packages/tmt/base.py	2021-11-16 14:34:21.000000000 +0100
+++ /usr/lib/python3.6/site-packages/tmt/base.py.new2	2021-11-18 15:48:50.456475166 +0100
@@ -1162,9 +1162,18 @@
         conditions = (conditions or []) + list(Test._opt('conditions', []))
 
         # Build the list and convert to objects
-        return self._filters_conditions(
-            [Test(test) for test in self.tree.prune(keys=keys, names=names)],
-            filters, conditions)
+        if names:
+            tests = []
+            for name in names:
+                tests.extend(
+                    self._filters_conditions(
+                        [Test(test) for test in self.tree.prune(keys=keys, names=[name])],
+                        filters, conditions))
+            return tests
+        else:
+            return self._filters_conditions(
+                [Test(test) for test in self.tree.prune(keys=keys)],
+                filters, conditions)
 
     def plans(self, keys=None, names=None, filters=None, conditions=None,
               run=None):
```

**Comment by psss** [comment]
Looks fine. We'll need some adjustments though 'cause currently command line selection results in duplicate test:

```
tmt run -v discover plan -n core test -n smoke
...
        summary: 2 tests selected
            /tests/core/smoke
            /tests/core/smoke
```

Seems to be caused by `Test._opt('names', [])` being applied twice.

**Comment by kkaarreell** [comment]
Would we able to find a reasonable use case for each of those? For me plan is questionable (repetitive executions) , for the rest I do not have it.

**Comment by lukaszachy** [comment]
I'd say that for `ls` and `show` there is no use case for order/duplication.

**Comment by juk** [comment]
I do not think there is a need for this in ls and show

**Comment by psss** [comment]
Ok, then the patch provided by @kkaarreell should be enabled only upon explicit request by adding a new parameter to the `tests()` method because currently the change affects command line as well.

**Comment by kkaarreell** [comment]
Can we enforce it using an additional attribute to the discover key?

**Comment by kkaarreell** [comment]
I am not familiar with tmt code enough to identify all places requiring an update. What about this?
```
# diff -u /usr/lib/python3.6/site-packages/tmt/base.py.orig /usr/lib/python3.6/site-packages/tmt/base.py
--- /usr/lib/python3.6/site-packages/tmt/base.py.orig	2021-11-18 19:35:18.467337852 +0100
+++ /usr/lib/python3.6/site-packages/tmt/base.py	2021-11-18 20:34:11.491621018 +0100
@@ -1153,7 +1153,7 @@
         """ Metadata root """
         return self.tree.root
 
-    def tests(self, keys=None, names=None, filters=None, conditions=None):
+    def tests(self, keys=None, names=None, filters=None, conditions=None, unique=True):
         """ Search available tests """
         # Handle defaults, apply possible command line options
         keys = (keys or []) + ['test']
@@ -1162,9 +1162,18 @@
         conditions = (conditions or []) + list(Test._opt('conditions', []))
 
         # Build the list and convert to objects
-        return self._filters_conditions(
-            [Test(test) for test in self.tree.prune(keys=keys, names=names)],
-            filters, conditions)
+        if unique == False and names:
+            tests = []
+            for name in names:
+                tests.extend(
+                    self._filters_conditions(
+                        [Test(test) for test in self.tree.prune(keys=keys, names=[name])],
+                        filters, conditions))
+            return tests
+        else:
+            return self._filters_conditions(
+                [Test(test) for test in self.tree.prune(keys=keys, names=names)],
+                filters, conditions)
 
     def plans(self, keys=None, names=None, filters=None, conditions=None,
               run=None):
```
and
```
# diff -u /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py.orig /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py
--- /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py.orig	2021-11-18 20:34:53.551993437 +0100
+++ /usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py	2021-11-18 20:36:07.215645692 +0100
@@ -220,7 +220,7 @@
             return
         tree = tmt.Tree(path=tree_path, context=self.step.plan._fmf_context())
         self._tests = tree.tests(filters=filters, names=names,
-                                 conditions=["manual is False"])
+                                 conditions=["manual is False"], unique=False)
 
         # Prefix tests and handle library requires
         for test in self._tests:

```
This seems to work for me:
```
$ tmt tests ls tpm tpm
/setup/configure_tpm_emulator
$ tmt run discover -v plan --name keylime-tests-github-ci -vvv
/var/tmp/tmt/run-087

/plans/keylime-tests-github-ci
summary: Tests used by Packit/TFT CI on Github
    discover
        how: fmf
        directory: /home/ksrot/devel/github/keylime-tests
        hash: 1bb26dc
        names: /setup/configure_tpm_emulator, /setup/install_upstream_keylime, /functional/basic-attestation-on-localhost and /functional/.*
        summary: 4 tests selected
            /setup/configure_tpm_emulator
            /setup/install_upstream_keylime
            /functional/basic-attestation-on-localhost
            /functional/basic-attestation-on-localhost
```

**Comment by psss** [comment]
This looks good. Would you mind creating a pull request with the change proposed above?

**Comment by kkaarreell** [comment]
Thank you @psss . Here it goes
https://github.com/psss/tmt/pull/950
