### ISSUE TITLE
Add support for specifying a concrete machine hostname

### ISSUE THREAD

**Issue by thrix** [psss/tmt#942]
Seems it could be valuable for some cases to be able to specify a concrete Beaker machine in hardware specification. This make come handy to @ksrot sooner or later, where he would like to run tests for specific machines which support `TPM.

**Comment by thrix** [comment]
@happz PTAL

**Comment by happz** [comment]
I for one would see this as two issues, "require TPM" and "require hostname". I suppose that the former can be replaced with the latter when the provisioner isn't able to find out whether machines available to it do or do not have TPM available.

**Comment by jirka-h** [comment]
For the Kernel Performance testing, this is a critical requirement. We need to run the tests on a specific host to ensure we are comparing apples to apples (performance numbers produced on the same HW).

Thanks a lot
Jirka

**Comment by thrix** [comment]
spec defined, we will need to discuss a bit the details I guess. 

See the PR pls ...
