### ISSUE TITLE
Please, provide support for beakerlib's rlFileSubmit()

### ISSUE THREAD

**Issue by rh-mcermak** [psss/tmt#963]
Please, provide support for beakerlib's rlFileSubmit().  Thanks.

**Comment by psss** [comment]
The support for `rlFileSubmit` has been merged in #918 just recently and has been released in `1.9`. Could you please try with the latest package from copr and verify it works as expected?

**Comment by lukaszachy** [comment]
Just a note that at this moment it just copies files into workdir (which is later pulled to the host). There is plan (idea) for #280 which could hold path to this files so they are discoverable and visible in reports.

**Comment by psss** [comment]
Should be covered by #918.
