### ISSUE TITLE
Provide path to the worktree during test execution

### ISSUE THREAD

**Issue by thrix** [psss/tmt#971]
Looks to me it could come handy to be able to run tests in workdir if requested, or provide an environment variable so we can easily remve workarounds like this one:

https://gitlab.com/testing-farm/tests/-/blob/main/gating/validity/test.sh#L6

Here I want to reference the target repository as I need to validate gaitng.yaml with it

Related to https://issues.redhat.com/projects/OSCI/issues/OSCI-2411

**Comment by thrix** [comment]
@lukaszachy @psss do we have somwhere a solution coming for this? Maybe it is a dupe ...

**Comment by psss** [comment]
Recently we've brainstormed on the hacking session that there could be a `TMT_TREE` variable with path to the `plan/tree` directory exported and available to tests so that they can perform actions there if needed. Would that cover this use case?

**Comment by thrix** [comment]
definitely, it would!
