### ISSUE TITLE
Incompatible environment variable name `REBOOT_COUNT`

### ISSUE THREAD

**Issue by pcahyna** [psss/tmt#991]
Calling the variable that counts reboots `REBOOT_COUNT` (https://tmt.readthedocs.io/en/latest/stories/features.html#reboot-during-test) seems to contradict "The functionality is compatible with how restraint works", because restraint does not have such variable (at least not documented). According to https://restraint.readthedocs.io/en/latest/remove_rhts.html?highlight=rebootcount#legacy-rhts-task-environment-variables it has `REBOOTCOUNT` (note the missing underscore) and `RSTRNT_REBOOTCOUNT` .

_Originally posted by @pcahyna in https://github.com/psss/tmt/pull/805#r774589982_

**Comment by psss** [comment]
Thanks for catching this inconsistency. We definitely wanted to keep the variable name consistent with what was used in the old tests to make the migration as easy as possible. Will have a look at this.
